### ISSUE TITLE
Add documentation for `docker.Image`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-docker#111]
The `Image` resource is not documented at https://www.pulumi.com/docs/reference/pkg/docker/.

We will need to add an overlay similar to https://github.com/pulumi/docs/pull/2980.  

Eventually, we will want to schematize `Image` and generate docs in a first-class way based on the capabilities added to support https://github.com/pulumi/pulumi/issues/2430.

**Comment by joeduffy** [comment]
@lukehoban I just noticed now that there isn't any resource-level documentation for `Image` (it's missing entirely from [this page](https://www.pulumi.com/docs/reference/pkg/docker/)). Is this dependent on the multi-language components workstream?
