### ISSUE TITLE
Dotnet SDK

### ISSUE THREAD

**Issue by floyd-may** [pulumi/pulumi-docker#116]
Is there a plan to support `pulumi-docker` in dotnet?

**Comment by lukehoban** [comment]
Yep - it’s actively being worked on in https://github.com/pulumi/pulumi-docker/pull/115.

**Comment by mikhailshilkov** [comment]
We've been using a meta-issue https://github.com/pulumi/pulumi/issues/3470 so far, we might split it up soon

**Comment by mikhailshilkov** [comment]
.NET SDK has shipped in 1.0 of this provider

**Comment by mikhailshilkov** [comment]
I should mention that the current version of the .NET SDK is mainly focused on the `Image` component. If you need other bits, feel free to open another issue.
