### ISSUE TITLE
Image build cacheFrom property does not match Docker CLI functionality

### ISSUE THREAD

**Issue by bob-bins** [pulumi/pulumi-docker#127]
Docker CLI allows you to specify another image to use as the cache source. Pulumi only allows you to use the same image that you're building as a cache source. This is problematic if one wants their images to be immutable. It would be great if you could also specify an arbitrary image as the cache source in Pulumi.

[Docker CLI](https://docs.docker.com/engine/reference/commandline/build/):
`--cache-from   Images to consider as cache sources`

[npm @pulumi/docker@1.1.0](https://github.com/pulumi/pulumi-docker/blob/382476abd12673abc97e08da8e4b5f3849858e06/sdk/nodejs/docker.ts#L74):
```
/**
 * An optional CacheFrom object with information about the build stages to use for the Docker
 * build cache. This parameter maps to the --cache-from argument to the Docker CLI. If this
 * parameter is `true`, only the final image will be pulled and passed to --cache-from; if it is
 * a CacheFrom object, the stages named therein will also be pulled and passed to --cache-from.
 */
cacheFrom?: pulumi.Input<boolean | CacheFrom>;
```

**Comment by guineveresaenger** [comment]
This is fixed via #500 and #467.
