### ISSUE TITLE
Go support + examples

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-docker#128]
See: 
1. https://github.com/pulumi/pulumi-docker/pull/115
2. https://github.com/pulumi/examples/pull/482

**Comment by tasiah** [comment]
FYI Erin talked to Lee earlier today and said it was fine for me to start working on this now.

**Comment by tasiah** [comment]
Could we break this down into smaller, testable steps? I started working on this and feel a bit intimidated by the amount of code that is seemingly necessary just to make Images work.

cc @lukehoban

**Comment by lukehoban** [comment]
I think the full scope of the work is effectively the same changes made in https://github.com/pulumi/pulumi-docker/pull/115.

As for order to pick of independently testable pieces - something like this probably makes sense:
1. `RunCommandThatMustSucceed`
1. `RunDockerBuild` 
1. Everything in `Utils`
1. `LoginToRegistry`
1. `BuildImageAsync`
1. `TagAndPushImageAsync`
1. `BuildAndPushImageWorkerAsync`
1. `BuildAndPushImageAsync`
1. `Image` itself
