### ISSUE TITLE
Python variant missing DockerBuild

### ISSUE THREAD

**Issue by adir-intsights** [pulumi/pulumi-docker#129]
I'm trying to add a local `docker build` step using the Python `pulumi-docker` package, it seems that there is no way to issue a docker build using the existing classes.

**Comment by stack72** [comment]
Hi @adir-intsights 

I am not quite sure what you mean by a `docker build` step - do you mean the equivalent of docker.Image which will build a container?

Paul

**Comment by adir-intsights** [comment]
@stack72 I'm more interested in the resulting image than the container. At [sdk/nodejs/image.ts](sdk/nodejs/image.ts) you can see `ImageArgs` have the `build` property so the user can pass a dockerfile file and a context to build a local docker image.

**Comment by lukehoban** [comment]
Yes - the `Image` class from this library is currently only available in TypeScript.  We will need to make it available for all languages.

**Comment by stack72** [comment]
Closed via #141 and #147
