### ISSUE TITLE
Diffs in Docker builds don't show up as diffs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-docker#131]
Due to the way we perform Docker builds, the `Image` resource never shows any diffs. This is confusing because, even if there are "no changes" shown, performing a `pulumi up` actually runs the command to perform the side effects of building and pushing the image.

Instead, I believe we should do the build and _either_ use the resulting digest hash as an input property for the resource -- such that if the hash changes, it appears as a diff to the resource -- or, if that's not appealing, we should treat changes to output properties as a diff in the output.

**Comment by lukehoban** [comment]
I believe this is (another) reason why we need to do https://github.com/pulumi/pulumi-docker/issues/132 (just opened to track more explicitly).

**Comment by dbeattie71** [comment]
I was just looking at how this works and I'm not sure docker inspect will work for coming up with a hash of an image on two different machines.  Does that sound right?  It would be nice to override the funtionality in BuildImageAsync that gets the inspectResult so a custom implementation can be created.

**Comment by leezen** [comment]
Cross-posting for posterity, but one option is to use the `RegistryImage` resource (see #132 (comment) for more details on using it as a replacement for `Image`)

**Comment by AaronFriel** [comment]
This issue is resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)! See our blog post for more info: https://www.pulumi.com/blog/build-images-50x-faster-docker-v4/
