### ISSUE TITLE
Secrets in registry login info taint entire Image outputs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-docker#145]
If I want to build and publish to a private container registry, using the `Image` class, it's common to need to supply authentication information in the program. (For example, see below for a full working example that publishes to the Docker Hub.) Unfortunately, I think [because of how we do a `pulumi.output(args).apply` for the entire set of arguments](https://github.com/pulumi/pulumi-docker/blob/458cfb1772a33c404ffcf9edda9f18082fd2b4ec/sdk/nodejs/image.ts#L110), the resulting build image information is marked secret.

For example:

```typescript
import * as docker from "@pulumi/docker";
import * as pulumi from "@pulumi/pulumi";

// Fetch the Docker Hub auth info from config.
const config = new pulumi.Config();
const username = config.require("dockerUsername");
const password = config.requireSecret("dockerPassword");

// Build and publish the image.
const image = new docker.Image("my-image", {
    build: "./app",
    imageName: `${username}/myapp`,
    registry: {
        server: "docker.io",
        username: username,
        password: password,
    },
});

// Export the resulting base name in addition to the specific version pushed.
export const baseImageName = image.baseImageName;
export const imageName = image.imageName;
```

After running this, I get:

```
Outputs:
  + baseImageName: "myuser/myapp"
  + imageName    : "[secret]"
```

If I whack the `isSecret` property, I can get it to output what I would have expected:

```
  + baseImageName: "myuser/myapp"
  + imageName    : "myuser/myapp:b54ab9f10546c5d8f67318c8bdd5ffcdf3a4d679bd8f34aac263c701245dfc67"
```

It would be best if we could avoid tainting the output since you need this to interact with the image, either to publish for other downstream services or stacks to consume or, as is the case with this program, exporting it for easy access from scripts/CLI commands.

**Comment by AaronFriel** [comment]
@guineveresaenger I've added this for us to re-triage, I believe this is resolved by moving to the CustomResource. We should be able to check the example in the issue quickly to verify.

**Comment by AaronFriel** [comment]
@joeduffy This issue is resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)!
