### ISSUE TITLE
mounting volumes options (shared, etc)

### ISSUE THREAD

**Issue by rienafairefr** [pulumi/pulumi-docker#152]
This is probably a shortcoming coming from terraform, but with pulumi-docker it's impossible to mount volumes with different kind of bind propagation (see https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation#configure-bind-propagation), like `rshared`.

The underlying issue in the terraform provider: https://github.com/terraform-providers/terraform-provider-docker/pull/130

**Comment by leezen** [comment]
Thanks for pointing this out. I'll close this out as we'll track this via the upstream issue.
