### ISSUE TITLE
Make docker registry credentials optional

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi-docker#16]
My team uses gcr as registry with the docker gcr credential helper which _automatically_ handles authentication and uses short lived access tokens behind the scenes. Hence it'd like to omit the username and password in the `registry` config of `docker.Image`. This is currently not possible. 
In fact when I currently attempt to omit them via
```ts
registry : {
  server: 'gcr.io',
  username: undefined as any,
  password: undefined as any
};
```
`pulumi up` gets stuck for **minutes** with the message
` info: [runtime] logging in to registry...` and I have to manually kill it, which is certainly a bug :)

**Comment by lukehoban** [comment]
Thanks @geekflyer.  We should indeed make sure this can work (and fix the issue with the login hanging!).

**Comment by joeduffy** [comment]
@hausdorff I just hit this myself -- it seems without this, there's no way to publish to a GCR registry.

**Comment by mazamats** [comment]
This should also solve https://github.com/pulumi/pulumi-docker/issues/24

If the login is performed outside pulumi (with a cli command beforehand), the login would be redundant.
