### ISSUE TITLE
docker container labels fail updates

### ISSUE THREAD

**Issue by rienafairefr** [pulumi/pulumi-docker#162]
I have a weird issue in creating and modifying docker containers, specifically when labels are involved. I was trying to use traefik in a compose-like manner, multiple-containers on single host, and using quite a lot of labels, and receiving `Expected diff to not require deletion or replacement during Update` whend updating :-( e.g. a container diff marks an update (because I modified a label, or added one), but the update fails, and the whole stack fails to deploy. This was on a remote host (Docker provider through a docker host `ssh://user@ip`)
The only way to fix was manually delete the container and `state delete` the pulumi resource.
I don't have a log handy, I should try to make a small reproducible example. 

This made me abandon pulumi for that part and use a good ol' docker-compose.yml, which kinda makes me sad

Pulumi version: 1.14, but seen the problem on previous versions as well. No other problems with the pulumi-docker stuff **unless** I triy to update containers labels. 

This might be a terraform bug with the labels (traefik labels use `.` in the key, and there's a discussion about `.` in label keys [here](https://github.com/terraform-providers/terraform-provider-docker/issues/214).

**Comment by jaxxstorm** [comment]
Hey @rienafairefr - thanks for opening the issue. Do you have some code I can look at to repro this? You might be right about the `.` in label keys, but let's see if we can find a fix/workaround!

**Comment by mikhailshilkov** [comment]
Since this issue is 3+ years old and we haven't heard back, I'll go ahead and close it as stale with no repro attached
