### ISSUE TITLE
Add back Python Docker Image build support

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-docker#164]
We are temporarily reverting the Python Docker Image build support (https://github.com/pulumi/pulumi-docker/pull/163) due to some subtle concurrency issues, to unblock the 2.0 release. This issue tracks addressing the concurrency issues and adding it back.

**Comment by dokuboyejo** [comment]
@justinvp @stack72 any idea when this might be available?

**Comment by stack72** [comment]
Hi @justinvp 

#160 is in progress to fix the issue we reverted
