### ISSUE TITLE
python local docker image not available

### ISSUE THREAD

**Issue by dokuboyejo** [pulumi/pulumi-docker#167]
Currently unable to create a container from locally build image.
github.com/pulumi/pulumi-docker/sdk/python/bin/pulumi_docker/docker.py is missing
Is there any plans for https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/docker/#Image to be available in the python variation?

**Comment by stack72** [comment]
Hi @dokuboyejo 

My apologies that you are facing this issue - we are actually tracking this in #164 so I am going to close this out and use that as the central issue to track this via

Thanks

Paul
