### ISSUE TITLE
Dependencies on docker images run before image is built and pushed

### ISSUE THREAD

**Issue by ddunkin** [pulumi/pulumi-docker#18]
If I have an image I'm building:
```typescript
const image = new docker.Image('myimage', {
  imageName: `myorg/myimage`,
  build: './myimage',
  registry,
});
```

and a Kubernetes deployment that depends on that image:
```typescript
const deployment = new k8s.apps.v1.Deployment('mydeployment', {
  spec: {
    template: {
      spec: {
        containers: [
          {
            image: image.imageName,
...
```

a `pulumi up` will create the deployment before the image is pushed. `image.imageName` will be invalid because `digest` will be empty. The deployment should not be created (or updated) until after the image has been pushed.

**Comment by ddunkin** [comment]
As a workaround, I use `image.baseImageName` and manually change the tag on the image whenever I change its contents. There's an image pull error when the deployment is first created, but that's easily addressed.

**Comment by CyrusNajmabadi** [comment]
This should be fixed as of https://github.com/pulumi/pulumi-docker/pull/31.  The 'imageName' is now the unique name.  And you shoud only be able to get this one hte docker build and push has completed.
