### ISSUE TITLE
Python: Apply() against image_name fails to return string

### ISSUE THREAD

**Issue by jkrusic19** [pulumi/pulumi-docker#180]
Hello,

When building an `Image()` from the Python Alpha pulumi-docker package, 2.2.0a1590012385, and applying the `image_name` to the Task Definition with use of `Outputs().apply()`, or just `Apply()` it fails to output the result of the resource. Diff always shows the output being  `<pulumi.output.Output object at 0x7fb9b0809cd0>`

Example Code:

- Image Build
`ui_image=Image(
    "%s-ui:latest" % p_application,
    build=DockerBuild(
        dockerfile = "../app/single.Dockerfile",
        context = "../app"
    ),
    image_name = repo.repository_url,
    registry = registry
)`

- Task Definition: container_definition json str
`imagetest = pulumi.Output.all(ui_image.image_name, p_ui_container_port, p_env, p_application).apply(lambda vals: f"""
[{{
            "portMappings": [{{
			    "containerPort": "{vals[1]}",
			    "protocol": "tcp"
		    }}],
            "name": "{vals[2]}_{vals[3]}_ui",
            'image': "{vals[0]}",
            'environment': [{{
                'name': 'ENV',
                'value': "{vals[2]}"
            }}]
    }}]
""")`

- Result
`"[{\"portMappings\": [{\"containerPort\": 80, \"protocol\": \"tcp\"}], \"name\": \"sandbox_app_ui\", \"image\": \"<pulumi.output.Output object at 0x7faf0028a990>\", \"environment\": [{\"name\": \"ENV\", \"value\": \"sandbox\"}]}]"`

- Expected Result
`"[{\"portMappings\": [{\"containerPort\": 80, \"protocol\": \"tcp\"}], \"name\": \"sandbox_app_ui\", \"image\": \"AWSACCOUNT.dkr.ecr.REGION.amazonaws.com/sandbox/app-ui:latest\", \"environment\": [{\"name\": \"ENV\", \"value\": \"sandbox\"}]}]"`

**Comment by komalali** [comment]
@jkrusic19 thanks for reporting this. I'm not being able to repro this issue, can you please share more code for your `Task Definition`? Something that's standing out to me is that your `container_definitions` need to be a json string, but your code includes single quotes for `'image'` amongst other things - and single quotes are not allowed in json.

**Comment by komalali** [comment]
Resolved this issue with the user, it seems like the error they were seeing was caused by the single quotes.
