### ISSUE TITLE
Ephemeral Docker build messages missing from Python

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-docker#181]
In our TypeScript implementation, we get ephemeral log messages when the Docker build is running, helping to understand progress (e.g., docker login commands, running specific build commands, pushing to the registry, etc). It looks like our Python library doesn't do the same kind of logging (not sure about .NET or Go yet). Because this can take some time and even fail part-way through, these messages are quite helpful to get a sense of what's happening and when.

**Comment by joeduffy** [comment]
FWIW, .NET and Go seem fine here.

**Comment by komalali** [comment]
Thanks for flagging this. I just worked on this so will look into it.

**Comment by komalali** [comment]
Okay so I thought this was something in the docker build code specifically but there's nothing weird I can see there. From as far as I could get with it I traced it back to this function in the python sdk: https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/log.py#L93-L113

This is deeper than I expected though so gonna let this go through regular prioritizing.

**Comment by AaronFriel** [comment]
This issue is resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)!
