### ISSUE TITLE
Building an image without a tag fails in Go

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-docker#183]
I believe this logic is reversed:

https://github.com/pulumi/pulumi-docker/blob/ea1aef9e4b0f9c5c801daaa09dc15ab966902eba/sdk/go/docker/image.go#L75-L80

The net result is that if you try to build an image that does _not_ have a tag, the second branch is taken, which appends `:` followed by the tag ... which is empty.

This fails in the following way:

```
error: program failed: docker image inspect -f {{.Id}} 153052954103.dkr.ecr.us-west-2.amazonaws.com/my-repo-215bfc3: failed with error: exit status 1

error: invalid argument "153052954103.dkr.ecr.us-west-2.amazonaws.com/my-repo-215bfc3:" for "-t, --tag" flag: invalid reference format
    See 'docker build --help'.

    error: Error response from daemon: no such image: 153052954103.dkr.ecr.us-west-2.amazonaws.com/my-repo-215bfc3:: invalid reference format
```

Notice that it fails on the `inspect` call due to another bug: https://github.com/pulumi/pulumi-docker/issues/182.

The workaround is to pass a tag, such as `latest`; for instance:

```go
image, err := docker.NewImage(ctx, "my-image", &docker.ImageArgs{
	Build: &docker.DockerBuildArgs{Context: pulumi.String("app")},
	ImageName: repo.RepositoryUrl.ApplyString(func(url string) string {
		return url + ":latest"
	}),
	Registry: registry,
})
```

**Comment by stack72** [comment]
great catch! You are correct - this needs to be inverted!
