### ISSUE TITLE
Design a better user-facing API

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-docker#2]
The current API exposed to build and push an image is pretty awkward.  Here's an example usage:

```typescript
let redisImage = docker.buildAndPushImage("lukehoban/redise2e", "./app", "lukehoban/redise2e", redisMasterService, async () => ({
    registry: "docker.io",
    username: "lukehoban",
    password: "password"
}));

// image: redisImage.apply(_ => "lukehoban/redise2e"),
```

Issues with this:
1. The image name is repeated twice
1. The name of the API is very low level.  Users want to think of this as something more like `new Image`
1. Passing the registry and username/password as a callback instead of as direct values is very unexpected.
1. The return value is not an image name I can use (it's a SHA hash) (so I have to do the weird `.apply(_ => "lukehoban/redise2e")` 
1. The documentation of almost all these inputs is unclear on what kind of values are needed

**Comment by joeduffy** [comment]
I think this could be as straightforward as the following addition:

```typescript
export class Image extends pulumi.ComponentResource {
    public readonly repo: pulumi.Output<string>;
    public readonly registry: pulumi.Output<Registry>;
    public readonly digest: pulumi.Output<string>;

    constructor(name: string, args: ImageArgs, opts?: pulumi.ComponentResourceOptions) {
        super("docker:container:Image", name, {}, opts);
        this.repo = args.repo;
        this.registry = args.registry;
        this.digest = buildAndPushImageAsync(name, args.build, args.repo, this, () => args.registry);
        super.registerOutputs({
            repo: this.repo,
            registry: this.registry,
            digest: this.digest,
        });
    }
}

export class ImageArgs {
    build: string | DockerBuild;
    repo: pulumi.Input<string>;
    registry: pulumi.Input<Registry>;
}
```

This lets you create a new Docker image simply through:

```typescript
const img = new docker.Image("lukehoban/redise2e", {
    build: "./app",
    repo: "lukehoban/redise2e",
    registry: {
        registry: "docker.io",
        username: "lukehoban",
        password: "password"
    },
});
```

I'd like to extend the type with an easy way to get the URL as an output property, `img.url`, although I'm not sure if this is just appending the repo name to the registry URL or something more complex.

I'll keep tinkering down this path but early feedback would also be great.

**Comment by lukehoban** [comment]
I've got some work in progress on this along very similar lines to @joeduffy's note above.  I'll open a PR for that shortly.
