### ISSUE TITLE
Cannot interpolate image name

### ISSUE THREAD

**Issue by ninja-** [pulumi/pulumi-docker#205]
```
    Error: [repositoryUrl] should not contain a tag:  pulumi.interpolate `prefix${v}suffix`
    
    See https
        at checkRepositoryUrl (/home/user/IdeaProjects/banana/node_modules/@pulumi/docker.ts:218:15)
```

Setting imageName to anything "dynamic" such as output from repository object results in this error....
Workaround is to hardcode registry url in code once created.
(image name is repository url + project name)

**Comment by lukehoban** [comment]
I’m not sure I follow what code you wrote that triggered this. Strictly speaking it definitely is not true that interpolated values are not supported here - but the values produced by those interpolations may be restricted in certain ways based on what you are trying to do with them. Can you share a code snippet that reproduce this?

**Comment by ninja-** [comment]
```
export const repo = new digitalocean.ContainerRegistry("registry");
const cred = new digitalocean.ContainerRegistryDockerCredentials("registry", {
  registryName: repo.name,
  write: true,
  expirySeconds: 3600 * 24 * 365 * 5,
});
export const registryEndpoint = repo.endpoint;
export const registryCred = cred.dockerCredentials.apply(data => {
  let a = new Buffer(JSON.parse(data)['auths']['registry.digitalocean.com']['auth'], 'base64').toString('ascii').split(':');
  return { username: a[0], password: a[1] };
const registryImage = new docker.Image("image", {
  imageName: repo.endpoint + "/registry",
  // localImageName: repo.endpoint + "/registry",

  registry: {
    //     Error: [repositoryUrl] should not contain a tag:  pulumi.interpolate `prefix${v}suffix`
    server: repo.endpoint + "/registry",// repo.endpoint, // repo.endpoint,
    password: registryCred.password,
    username: registryCred.username
  },
  build: {
    context: "../container-registry",

  },
});

```

**Comment by ninja-** [comment]
@lukehoban :thinking:

**Comment by Bj3MaS** [comment]
Got same error when i did following, 

`${pulumiHeleper.docker.getContainerRegistry().server}/${serviceName}:${git.short()}` change to this fixed my problem
``pulumiHeleper.docker.getContainerRegistry().server.apply(server => { return `${server}/${serviceName}:${git.short()}`}),``

**Comment by imajus** [comment]
Don't forget that you have to interpolate the outputs from Pulumi resources when you're using them in a custom string:
```
registry: {
    server: pulumi.interpolate`${repo.endpoint}/registry`,
    password: registryCred.password,
    username: registryCred.username
  },
```

**Comment by AaronFriel** [comment]
This issue should be resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)! See our blog post for more info: https://www.pulumi.com/blog/build-images-50x-faster-docker-v4/

Inputs to the new Image resource are no longer handled in a language-specific manner, and now behave as expected of a standard Pulumi resource.
