### ISSUE TITLE
Can't set Docker API Version with pulumi

### ISSUE THREAD

**Issue by virendragteam** [pulumi/pulumi-docker#220]
I am deploying docker container on our docker host which support docker API version 1.39 but not latest one (1.40)

From docker cli, we can set version and can connect to docker host.
`export DOCKER_API_VERSION=1.39`

However with pulumi, it's not working

There is no option to set API version https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/docker/config/
When deploy with pulumi, I am getting error

`error: Error pinging Docker server: request returned Internal Server Error for API route and version https://DNS:PORT/_ping, check if the server supports the requested API version`

I am using below config with pulumi in my yaml file.
```
docker:host: "tcp://DNS:PORT
docker:certPath: "valid path to docker-cert"
docker:tlsVerify: 1
docker:apiVersion: 1.39
```

I set `export DOCKER_API_VERSION=1.39` on my terminal and then run pulumi script - 
it picked up `host` and `certPath` from yaml but do not pick version from env or yaml and getting same error.

`error: Error pinging Docker server: request returned Internal Server Error for API route and version https://DNS:PORT/_ping, check if the server supports the requested API version`
`

**Comment by leezen** [comment]
The client instantiated is instantiated via `client.WithAPIVersionNegotiation` so there's no pinned API version. I would expect this to work without attempting to set the API version. Does verbose logging provide any additional debugging information?

**Comment by virendragteam** [comment]
Hi @leezen 

There is no more detail in verbose mode

```
➜  mta git:(pulumi) ✗ pulumi up -y -v 8
Previewing update (demo):
     Type                         Name       Plan     Info
     pulumi:pulumi:Stack          mta-demo
     └─ docker:index:RemoteImage  mta-image           1 error

Diagnostics:
  docker:index:RemoteImage (mta-image):
    error: Error pinging Docker server: request returned Internal Server Error for API route and version https://dl1.xxxxx.com:9998/_ping, check if the server supports the requested API version

```

can you please give an example how I can set up `client.WithAPIVersionNegotiation ` ?

**Comment by clstokes** [comment]
@virendragteam can you provide your Pulumi application code as well?

**Comment by AaronFriel** [comment]
@virendragteam We should be negotiating the API in the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)! See our blog post for more info: https://www.pulumi.com/blog/build-images-50x-faster-docker-v4/

As we're now calling the Docker client API via the Go SDK directly, I don't expect this to be an issue any longer. If this is, please let us know by filing a new issue.
