### ISSUE TITLE
ServiceTaskSpecContainerSpecArgs.Commands should be `Command`

### ISSUE THREAD

**Issue by koliyo** [pulumi/pulumi-docker#234]
To be consistent with `ContainerArgs.Command`, both should use singular `Command` instead of `Commands`?

**Comment by leezen** [comment]
Thanks for pointing out this inconsistency. Probably yes, but at this point it would be a breaking change to rename it as such. I'll leave this open to consider for when performing a major version bump of this package.

**Comment by lukehoban** [comment]
Closing out as by design for now.
