### ISSUE TITLE
Go: CacheFrom is currently unusable

### ISSUE THREAD

**Issue by mswartzendruber-discovery** [pulumi/pulumi-docker#238]
[DockerBuild.CacheFrom is currently defined as `*CacheFrom`](https://github.com/pulumi/pulumi-docker/blob/v2.4.0/sdk/go/docker/customTypes.go#L62). Since `CacheFromArgs.ElementType` returns [`reflect.TypeOf((*CacheFrom)(nil)).Elem()`](https://github.com/pulumi/pulumi-docker/blob/v2.4.0/sdk/go/docker/customTypes.go#L31) (the value rather than the pointer), it results in the following panic:
```
panic: cannot convert an input of type docker.CacheFromArgs to a value of type *docker.CacheFrom
    goroutine 175 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.awaitInputs(0x5328b20, 0xc0000e0068, 0x47e2c20, 0xc0001e2bf8, 0x194, 0x46a4ec0, 0xc0003d8038, 0x196, 0x5350000, 0x0, ...)
        /go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.13.2/go/pulumi/types.go:581 +0x2cf7
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.awaitInputs(0x5328b20, 0xc0000e0068, 0x47e2d20, 0xc00056c4c0, 0x94, 0x4890680, 0xc0003d8010, 0x199, 0x5350000, 0x0, ...)
        /go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.13.2/go/pulumi/types.go:664 +0x135c
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.awaitInputs(0x5328b20, 0xc0000e0068, 0x48907a0, 0xc00056c4b0, 0x99, 0x4872760, 0xc0003d8000, 0x199, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.13.2/go/pulumi/types.go:664 +0x135c
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.toOutputWithContext.func1(0x48907a0, 0xc00056c4b0, 0x534df40, 0xc0001e2e00, 0x535da80, 0x4872760, 0x5328b20, 0xc0000e0068, 0x535da00)
        /go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.13.2/go/pulumi/types.go:760 +0x153
    created by github.com/pulumi/pulumi/sdk/v2/go/pulumi.toOutputWithContext
        /go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.13.2/go/pulumi/types.go:752 +0x1e8
    exit status 2
```
_Note that the outcome is the same whether a `&CacheFromArgs{}` pointer or `CacheFromArgs{}` value is passed since it doesn't change the return value of `ElementType()`_

I tested out manually removing the `.Elem()` call (effectively making `ElementType` return `reflect.TypeOf((**CacheFrom)(nil)).Elem()`) and that seems to solve the issue. I believe there needs to be a `CacheFromPtr` type for the same reason there is the `pulumi.BoolPtr` type.

**Comment by paymog** [comment]
@leezen any idea on when this will be fixed? It's been almost 7 months since this was reported.
