### ISSUE TITLE
Feature Suggestion: Provide a way to login to docker on 'pulumi preview'

### ISSUE THREAD

**Issue by mswartzendruber-discovery** [pulumi/pulumi-docker#239]
Consider a scenario where your base image is from a private ECR repository that is a different repository from your push target. This works fine when doing `pulumi up`, but not on a `pulumi preview` [unless DockerBuild.CacheFrom is specified](https://github.com/pulumi/pulumi-docker/blob/v2.4.0/sdk/go/docker/docker.go#L47). Would it make sense to add another field to `DockerBuild` to force a login? Something that could be used like the following:

```go
if !ctx.DryRun() || pullFromCache || build.ForceLogin {
	logEphemeral(ctx, "Logging into registry...", logResource)
	err := loginToRegistry(ctx, *registry, logResource)
	if err != nil {
		return "", err
	}
}
```

**Comment by lukehoban** [comment]
Very good suggestion. Cc @stack72 who was mentioning a similar issue today.

**Comment by AaronFriel** [comment]
With the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0), the resource no longer builds image in preview. This should allow auth via `docker login` (via the Command provider) and other techniques to work as a workaround in case multiple registries are used as sources in a build.

@mswartzendruber-discovery Is that sufficient?
