### ISSUE TITLE
Logging into the same repository repeatedly

### ISSUE THREAD

**Issue by beetahnator** [pulumi/pulumi-docker#24]
Having issues dynamically provisioning Docker Builds on ECR.

With deploys done as nested components, pulumi attempts to login to the same registry multiple times.

https://dropbox.azam.at/Screen-Shot-2018-10-04-14-14-47.png

```
 +  docker:image:Image xxxxx:0.17.0 creating 1 warning, 3 info messages. warning: Error saving credentials: error storing credentials - err: exit status 1, out: `The specified item already exists in the keychain.`
 +  docker:image:Image xxxxxx:1.10.0 creating 1 warning, 3 info messages. warning: Error saving credentials: error storing credentials - err: exit status 1, out: `The specified item already exists in the keychain.`
 +  pulumi:pulumi:Stack xsxxxxx-xxxxxx-images **creating failed** 1 error, 1 info message. error: Failed to login to Docker registry https://xxxxxxx.dkr.ecr.xxxxxxxx.amazonaws.com
 +  pulumi:pulumi:Stack xxxxxxx-xxxxxxx-images **creating failed** 2 errors, 1 info message. error: Failed to login to Docker registry https://xxxxxxxxx.dkr.ecr.xxxxxxxx.amazonaws.com
```

**Comment by lukehoban** [comment]
@mazamats I'm not sure I understand the conditions that are leading to this.  Do you have a small repo, or more details on the setup?

**Comment by mazamats** [comment]
@lukehoban when you build multiple docker images and push them, pulumi will attempt to login to each images provided registry individually. Even if the registry is the same for all of the images.

![](https://dropbox.azam.at/Screen-Shot-2018-10-04-15-51-13.png)

On large deployments with several images it causes the following error from docker when the redundant login is attempted.

```
    warning: Error saving credentials: error storing credentials - err: exit status 1, out: `The specified item already exists in the keychain.`
```

**Comment by lukehoban** [comment]
#16 helps here - by making login optional.  But I suspect we can still improve by caching logins so that even if you do provide login credentials, we don't try to login multiple times.

I'm still not 100% sure I follow where the "error storing credentials" is coming from - do you have a credentials helper of some kind installed for ECR?

**Comment by mazamats** [comment]
It wasn't a credential helper, native Docker on Mac.

![](https://dropbox.azam.at/Screen-Shot-2018-10-16-at-2.59.46-PM.png)

**Comment by discovery-NukulSharma** [comment]
@mazamats -how did you manage to fix this/
