### ISSUE TITLE
Harness container registry examples as tests

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-docker#246]
In https://github.com/pulumi/pulumi-docker/commit/992cefda0a652e32efd911644d2fdcb7ae9bb0c4, we added a number of new container registry examples. Ideally we would run those as tests. For a few of them, that may require us to configure this repository to authenticate with new accounts (like DigitalOcean), although others should just work (like AWS).

**Comment by stack72** [comment]
The tests that need added:

* [ ] AWS
  * [ ] CSharp
  * [ ] JS
  * [ ] TS
  * [ ] Py
  * [ ] Go
* [ ] Azure
  * [ ] CSharp
  * [ ] JS
  * [ ] TS
  * [ ] Py
  * [ ] Go
* [ ] DigitalOcean
  * [ ] CSharp
  * [ ] JS
  * [ ] TS
  * [ ] Py
  * [ ] Go
* [ ] Docker
  * [ ] CSharp
  * [ ] JS
  * [ ] TS
  * [ ] Py
  * [ ] Go
* [ ] GCP
  * [ ] CSharp
  * [ ] JS
  * [ ] TS
  * [ ] Py
  * [ ] Go
* [ ] GCP K8s
  * [ ] CSharp
  * [ ] JS
  * [ ] TS
  * [ ] Py
  * [ ] Go
* [ ] Kubernetes
  * [ ] CSharp
  * [ ] JS
  * [ ] TS
  * [ ] Py
  * [ ] Go

**Comment by blampe** [comment]
@guineveresaenger took care of this in #502 #505 #515 #510 #521 etc!
