### ISSUE TITLE
Feature Request: Inline Dockerfile

### ISSUE THREAD

**Issue by johnhenry** [pulumi/pulumi-docker#271]
When building an image,  I would like the ability pass the content of a Dockerfile directly to the Image constructor, rather than having to reference an external context. e.g.:

```typescript
import { Image } from "@pulumi/docker";
const imageName = 'trial-image';

const base = 'ghost';
const exposedPort = 2368;
const localPort = 8080;
const buildingMessage = 'building a container...';

const image = new Image(imageName, {
  imageName,
  build: {
    context: `.`,
    dockerfileContent: `
    FROM ${base}
    RUN echo '${buildingMessage}'
    EXPOSE ${exposedPort}`
  },
  skipPush: true
}, {});
```

## Affected feature

It seems plausible  to modify the DockerBuild interface within "sdk/nodejs/docker.ts" and to modify **dockerBuild** to pass content as the *stdin* parameter to *runCommandThatMustSucceed** when appropriate.

I'm working on a branch here: https://github.com/johnhenry/pulumi-docker/tree/johnhenry/dockerfile-content, which seems to work for typescript, but i'm unclear on how to write tests that will be accepted for this project. 

I've also included updates for python, c#, and go; but I am not an expert with these languages an am unclear how to run and test them with my local branch.

**Comment by enricoschaaf** [comment]
What's the reason the PR has been closed?

**Comment by blampe** [comment]
Hi @johnhenry, we just released a new Docker Build provider focused exclusively on building images with buildx/BuildKit. It provides support for inline Dockerfiles out of the box, and we recommend you use it for building images going forward. Please take a look and give us feedback!

The repository is [here](https://github.com/pulumi/pulumi-docker-build); our blog announcement is [here](https://www.pulumi.com/blog/docker-build/); and finally API docs are [here](https://www.pulumi.com/registry/packages/docker-build/) along with examples of how to migrate your existing `Image` resources to `dockerbuild.Image`.

We won't be able to add this functionality in this provider for a number of reasons, so I'm closing this as wont-fix.

**Comment by mausch** [comment]
> We won't be able to add this functionality in this provider for a number of reasons

What are those reasons? Pulumi has a general problem with module overlap...
- https://github.com/pulumi/pulumi-docker vs https://github.com/pulumi/pulumi-docker-build
- https://github.com/pulumi/pulumi-awsx vs https://github.com/pulumi/pulumi-aws-native vs https://github.com/pulumi/pulumi-aws

You (the Pulumi dev team) might have technical reasons for doing things this way but ultimately it harms usability for end users.
