### ISSUE TITLE
Python SDK doesn't handle use of CacheFrom

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-docker#274]
I'm trying to use `--cache-from` to cache part of their docker build chain. It works in typescript but not in python.

## Expected behavior

When the code causes `docker build` to run, it should pass in the `--from-cache` argument.

## Current behavior

In typescript, [I can see it in the output](https://github.com/pierskarsenbarg/pulumi-demos/commit/ec2904054161c5471ba6c006949e3688367d7a71#diff-6e88fdced47e69a3db68c09a55ddb9986494f929cffab92aaa8935703839c305R261-R262)

It's [not there in python](https://github.com/pierskarsenbarg/pulumi-demos/blob/main/docker-cache-python/use-cache/out.txt#L245)

## Steps to reproduce

The [typescript implementation](https://github.com/pierskarsenbarg/pulumi-demos/blob/main/docker-cache/use-cache/index.ts#L12) works and if look at the output I can see it's there. 

If I do the [same but in python](https://github.com/pierskarsenbarg/pulumi-demos/blob/main/docker-cache-python/use-cache/__main__.py) it doesn't work.

**Comment by benesch** [comment]
I just ran into this and sent #299 to fix. As far as I can tell, the code to handle `cache_from` in Python was translated directly from the Node.js SDK and never actually tested.
