### ISSUE TITLE
docker login failed with exist code 1

### ISSUE THREAD

**Issue by thrixton** [pulumi/pulumi-docker#277]
When running on linux and doing a `new docker.Image(...`, with a `registry: {server: {azure container registry login server here}` , I'm getting the error `docker login failed with exit code 1`.  
Looking at the verbose logs, I see an error with the docker version script (`Executing ' docker version -f {{json .}}'`) which results in the error `eventSink::Info(<{%reset%}>Could not process Docker version (SyntaxError: Unexpected end of JSON input)<{%reset%}>)`  
I can manually do a docker login and then push with the login server and credentials I'm using in the stack so the credentials are correct.  

Docker is running as a snap  on ubuntu 20.04  
Running docker version I get 
```
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        cd8016b6bc
 Built:             Fri Feb  5 15:56:39 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf
  Built:            Fri Feb  5 15:58:24 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
## Expected behavior
Build and push works

## Example resource
```typescript
const appBaseImage = new docker.Image(`${componentName}-image`, {
    imageName: out.appBaseImageUri,
    build: {
      args: {
        UBUNTU_VERSION: "...",
        UBUNTU_RELEASE: "...",
        NODE_VERSION: "...",
        APP_VERSION: "...",
      },
      context: `./content/app-docker-base`,
    },
    registry: {
      server: k8sRegistryLoginServer,
      username: k8sRegistryUsername,
      password: k8sRegistryPassword,
    },
  });
```

## Context (Environment)
**Versions**
Pulumi: v2.25.2
@pulumi/docker: 3.0.0
## Affected feature
docker.Image

**Comment by leezen** [comment]
@thrixton Do you mind executing `docker version -f {{json .}}` and pasting the output here?

**Comment by thrixton** [comment]
Thanks @leezen , I get the below error on that :(  
"docker version" accepts no arguments.  
Yet `docker version --help` clearly gives the options for `-f, --format string`  

I presume this is causing my problem?

I'll try it with a manual install instead of the snap.

**Comment by leezen** [comment]
@thrixton Thanks for the update. Yes, the underlying code assumes it can determine the version in order to determine the correct format of the parameters for `docker login`

**Comment by thrixton** [comment]
Thanks @leezen , removing the snap and switching to the official CE version works.  
Note for future self and others, in both Linux and Windows, the format string must be wrapped in quotes. e.g. `docker version -f "{{json .}}"`
