### ISSUE TITLE
K8s deployment does not wait for docker image to be pushed before updating itself

### ISSUE THREAD

**Issue by bob-bins** [pulumi/pulumi-docker#291]
Not sure if this is the correct repo to report this in.

I'm using npm's `@pulumi/docker` to build an image and have a K8s deployment reference that image. When I run `pulumi up`, after it builds the image it pushes the image and at the same time updates the deployment container `image` property, which causes the pods to get `ErrImagePull`. If the image is large and takes a while to push, the deployment is guaranteed to fail after its exceeded the number of image pull retries.

I'd expect the image push to complete before any resources referencing that image are updated.

**Comment by bob-bins** [comment]
I'm using the `baseImageName` property. I tried to recreate this bug in another project and was not able to so I'm not sure what's going on. Here is my code:

```
const repo = new Repository("data-processor", {
  name: `orgname/data-processor/dev`,
})

const image = new docker.Image("data-processor", {
  imageName: interpolate`${repo.repositoryUrl}:test5`,
  build: {
    context: `../`,
    dockerfile: `../Dockerfile`,
    target: "release",
    args: {
      ssh_key_base64: 'redacted_string',
    },
  },
})

const labels = { app: "data-processor" }
const deployment = new Deployment(
  "data-processor",
  {
    metadata: {
      name: "data-processor",
    },
    spec: {
      replicas: 1,
      selector: {
        matchLabels: labels,
      },
      template: {
        metadata: {
          labels: labels,
        },
        spec: {
          containers: [
            {
              name: "data-processor",
              image: image.baseImageName,
              command: ["bash", "-c", "sleep 9999"],
            },
          ],
        },
      },
    },
  },
  { provider: config.eksProvider }
)
```

When I run `pulumi up` I see a diff of the deployment's image property

```
    ~ kubernetes:apps/v1:Deployment: (update)
        ...
      ~ spec: {
          ~ template: {
              ~ spec: {
                  ~ containers: [
                      ~ [0]: {
                              ~ image: "<redacted>.dkr.ecr.us-east-1.amazonaws.com/orgname/data-processor/staging:test4" => "<redacted>.dkr.ecr.us-east-1.amazonaws.com/orgname/data-processor/staging:test5"
                            }
                    ]
                }
            }
        }
```

Here is what I see when I select `yes` (you can see the image is still being pushed while a Deployment update is happening).

```
Updating (data-processor-staging):
     Type                               Name                                   Status       Info
     pulumi:pulumi:Stack                infrastructure-data-processor running.     
     ├─ docker:image:Image              data-processor                                      f5600c6330da: Layer already exists
 ~   └─ kubernetes:apps/v1:Deployment  data-processor                         updating     [diff: ~spec]; [1/3] Waiting for Deployment update to roll out (0/1 
```

Happy to jump on a call if necessary.

**Comment by viveklak** [comment]
@bob-bins thanks for the details! Could you try replacing the reference for `image.baseImageName` with `image.imageName` instead? The baseImageName is just the desired image name in the args returned back, where as imageName is the pinned version in the registry.

**Comment by bob-bins** [comment]
Thanks! `image.imageName` gives me the expected behavior, but I specifically want the value of `baseImageName` (the tag I chose without the extra long hash Pulumi appends to the end). I suppose I could truncate the value of `imageName` but is that the only way to get this to work?

**Comment by viveklak** [comment]
Something like this should do the trick:
```
image: image.imageName.apply(_ => image.baseImageName),
```

**Comment by bob-bins** [comment]
Thanks @viveklak!

**Comment by viveklak** [comment]
There is something to be said about perhaps changing semantics of `baseImageName` so it awaits the publish just as `imageName` does. It does seem to be somewhat befuddling behavior for users and the documentation doesn't really make the subtlety clear. Thoughts @leezen or @lukehoban?
