### ISSUE TITLE
Add built-in support for provisioning common private registries

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-docker#3]
The current `buildAndPushImage` assumes a registry already exists.  This package could also support provisioning of registries in common registries, like ECR, GCR, ACR, private DockerHub, etc.

**Comment by bobhenkel** [comment]
+1 ECR support.

**Comment by lukehoban** [comment]
As noted above, this is already possible to do manually, so the remaining question is which of the following we should do:
1. Leave this to be something users stitch together themselves, and include good examples/docs
2. Have `@pulumi/docker` take a dependency on AWS/Azure/GCP packages and add tools for auto-provisioning ECR/ACR/etc. as part of a `docker.Image`
3. `@pulumi/aws`/`@pulumi/azure` etc. take a dependency on `@pulumi/docker` and make platform-specific Docker image push easily available through APIs on `aws.ecr.Repository` or similar.

**Comment by CyrusNajmabadi** [comment]
We're going to take on the docker work in m20.

**Comment by lukehoban** [comment]
We're decided to do do something like (3) and put this into the `@pulumi/awsinfra` layer of libraries.  Closing out here - as we'l track this as part of the work in those - such as https://github.com/pulumi/pulumi-aws-infra/issues/53.
