### ISSUE TITLE
Switch away from needing a real repository Digest over to using just a 'docker image id'

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-docker#30]
Right now, we expose a docker repository's digest as part of our docker.Image API.  This is problematic as this is both hard to get, and requires actual communication with a repository to compute.  

The virtue of the digest though is that it is completely unique and is the best representation of the pushed image that anything else can depend on.

A way we can avoid doing this is do just use docker's image id and use that info instead.  This information is available locally using 'docker image inspect' and can then be used by pulumi.  To that end, we intend to take the image-id, and then encode that as a 'tag' for a image.  i.e. say we build a docker image, producing an image-id 'abcdef'.  We'd then push the image with the name `basename/name:abcdef`.  

This has certain benefits:

1. we can dependably compute this information locally.  
2. this information can be passed to someone else and used as a fully unique name for this pushed image (it should be as good as the repo digest version)
3. if anything changes this ID will change and will cause an update.
4. we no longer need to do things like encode the image-id into the 'environment' property like we do in cloud-aws/azure.

The downsides are:

1. This is pretty redundant with the digest that a normal docker repository creates.
2. users will be able to see these additionally tagged builds in their list of docker builds in the repository.
3. if the user provides their own tag as well, we'll end up having push twice.  i.e. if the user's image name is `basename/name:dev` we'll have to push both that *and* `basename/name:dev-abcdef`.  This isn't necessary normally, as repositories will normally give you a 'latest' tag that points to the last thing you pushed.

Overall, while there are a few cons, they don't seem that bad, and we believe they're far outweighed by the pros.

**Comment by CyrusNajmabadi** [comment]
Actually, i'm not certain if we need the `basename/name:dev-abcdef`.  it seems like it would be ok to just have hte tagged version based on hte user request (i.e. `basename/name:dev`) and then also have `basename/name:abcdef`  the former is just a nice tagged release.  THe latter is the unique name we can depend on.

**Comment by CyrusNajmabadi** [comment]
Talked with like.  The idea is this.  If *no* tags are provided, we push to:

`basename/name` and `basename/name:hash`

If a tag is provided we *only* push to:

`basename/name:tag` and `basename/name:tag-hash`.

**Comment by joeduffy** [comment]
@CyrusNajmabadi @pgavlin @hausdorff Who wants to take this one and figure out what to do here?

**Comment by CyrusNajmabadi** [comment]
Closing out.  This work was done in: https://github.com/pulumi/pulumi-docker/commit/57c6cae6871a2fb4bec5daa0c0738e04c5c64333
