### ISSUE TITLE
 error: program failed: waiting for RPCs: unexpected unknown property value

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-docker#308]
This program fails with `error: program failed: waiting for RPCs: unexpected unknown property value`.

```go
package main

import (
	"fmt"
	"time"

	"github.com/pulumi/pulumi-docker/sdk/v3/go/docker"
	"github.com/pulumi/pulumi-gcp/sdk/v5/go/gcp/artifactregistry"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		depStackName := "foo"
		depLocation := "us-central1"
		depProject := "pulumi-development"

		// Provision a Google Cloud Artifact Registry repo, and enable all
		// authenticated users to pull from and push to it.
		repoName := fmt.Sprintf("%s-repo", depStackName)
		repo, err := artifactregistry.NewRepository(ctx, repoName, &artifactregistry.RepositoryArgs{
			Location:     pulumi.String(depLocation),
			RepositoryId: pulumi.String(repoName),
			Format:       pulumi.String("DOCKER"),
		})
		if err != nil {
			return err
		}
		repoIAM, err := artifactregistry.NewRepositoryIamMember(
			ctx, repoName+"-iam", &artifactregistry.RepositoryIamMemberArgs{
				Location:   pulumi.String(depLocation),
				Repository: repo.Name,
				Role:       pulumi.String("roles/editor"),
				Member:     pulumi.String("allAuthenticatedUsers"),
			},
		)
		if err != nil {
			return err
		}

		// Build and publish our app to the repo.
		repoUrl := pulumi.Sprintf("%s-docker.pkg.dev/%s/%s/my-image", depLocation, depProject, repo.Name)
		image, err := docker.NewImage(ctx, "my-image", &docker.ImageArgs{
			ImageName: pulumi.Sprintf("%s:%d", repoUrl, pulumi.Int(time.Now().Unix())),
		}, pulumi.DependsOn([]pulumi.Resource{repoIAM}))
		if err != nil {
			return err
		}

		// Export the name of the bucket
		ctx.Export("imageName", image.ImageName)
		return nil
	})
}
```

Adding ` Registry:  docker.ImageRegistryArgs{},` to the `docker.NewImage` call causes it to succeed, but should not be required.  This is likely a deeper issue than just the Docker package, this error message should not really be possible to trigger from user code - it suggests there is some bug in the Go SDK or engine?

**Comment by joeduffy** [comment]
I wonder if it has to do with the unconditional conversion to an output/etc:

https://github.com/pulumi/pulumi-docker/blob/0a6928ef65763f30820837d63d3ad9e59ad993e1/sdk/go/docker/image.go#L87-L89

**Comment by lukehoban** [comment]
Yes - my assumption is that this is related somehow to that code - as the failure happens *after* the Docker build and push completes, and that code produces a value that flows int the RegisterResourceOutputs, which I'm assuming is where this fails.

**Comment by t0yv0** [comment]
Sounds concerning I'd like to dig into this in current iteration cc @emiliza

**Comment by johannesdrescher** [comment]
Unfortunately this is still a problem. And it's really weird too. I had code that did not use the workaround in production for months and the error never came up (yes, I was using the Go SDK and the latest version). I was setting up some new infrastructure when I ran into the issue.

**Comment by advanderveer** [comment]
Unfortunately I'm also running into this now. Kinda same story: it worked in another project, copied over the code and it stopped working and gave this error.

**Comment by AaronFriel** [comment]
This issue should be resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)! See our blog post for more info: https://www.pulumi.com/blog/build-images-50x-faster-docker-v4/
