### ISSUE TITLE
ECR login fails with Podman on my local system

### ISSUE THREAD

**Issue by nicolasochem** [pulumi/pulumi-docker#309]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We have enabled `cacheFrom` in our pulumi codebase to speed up container build in our github actions. In the absence of that, the github action would rebuild all containers from scratch.

Since I have done that, I am unable to do `pulumi preview/pulumi up` locally. The error is:

`"docker login" failed with exit code 125`

I am on Linux (Fedora 33) with podman aliased to docker, as per the official recommendation of the distro.

We are using AWS and ECR.

I was able to modify the pulumi-docker to print the entire `docker login` command. The issue seems to be that the last parameter of the command is `https://<registry hostname>`

Quoting this [blog post](https://marcusnoble.co.uk/2021-09-01-migrating-from-docker-to-podman/):

```
Podman seems more strict than Docker when parsing the config file, check the ~/.docker/config.json file for the key with the https:// prefix (as mentioned in the error message) and remove it.
```

It seems like removing `https://` from the docker login command would help. I verified by testing the `docker login` command manually. The parmeter should be the hostname of the repository only. I was not able to find where in the code the login happens for layer caching.

### Steps to reproduce

```
      let repo = ecrRepo ? ecrRepo : new awsx.ecr.Repository(pulumi.getStack())


      const registry = repo.repository.registryId.apply(async id => {
        let credentials = await aws.ecr.getCredentials({
          registryId: id
        }, {
          ...defaultResourceOptions,
          async: true,
        });

        let decodedCredentials = Buffer.from(credentials.authorizationToken, "base64").toString();
        let [username, password] = decodedCredentials.split(":");
        if (!password || !username) {
          throw new Error("Invalid credentials");
        }

        return {
          registry: credentials.proxyEndpoint,
          username: username,
          password: password,
        };
      })

      let _cacheFrom: docker.CacheFrom = {}

      const pulumiTaggedImages = Object.entries(tezosK8sImages).reduce(
        (obj: { [index: string]: any }, [key, value]) => {
          let dockerBuild: docker.DockerBuild = {
            dockerfile: `${k8sRepoPath}/${key}/Dockerfile`,
            cacheFrom: _cacheFrom,
            context: `${k8sRepoPath}/${key}`
          };
          obj[key] = docker.buildAndPushImage((value as string).replace(/:.*/, ""), dockerBuild, repo.repository.repositoryUrl, this, () => registry);
          return obj
        },
        {}
      )
```

If I comment out `      let _cacheFrom: docker.CacheFrom = {}` and ` cacheFrom: _cacheFrom,`, it works.

**Comment by leezen** [comment]
If it's the case that removing `https://` from Docker login works due to Podman being more restrictive, then you should be able to make this happen via code I believe because `credentials.proxyEndpoint` is what's embedding that `https://` so you should be able to simply strip that off w/in the code unless I'm missing something?

**Comment by nicolasochem** [comment]
You're not missing anything, I just didn't know enough :)

`registry: credentials.proxyEndpoint.replace("https://",""),` fixed it and didn't break it for my colleagues using docker on mac os x.

My issue is fixed, I'll leave it up to you to close or decide you want to strip https always within the library.

**Comment by deuscapturus** [comment]
This issue should be re-opened to allow https:// prefix.  This restriction currently breaks aws-cdk with podman.

```
current credentials could not be used to assume 'arn:aws:iam::00000000000:role/cdk-aaaaa-image-publishing-role-0000000000-us-west-2', but are for the right account. Proceeding anyway.
[100%] fail: docker login --username AWS --password-stdin https://00000000000.dkr.ecr.us-west-2.amazonaws.com exited with error code 125: Error: credentials key has https[s]:// prefix

 ❌  search-reporting-lambda-production failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (/usr/local/lib/node_modules/aws-cdk/lib/util/asset-publishing.ts:27:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CloudFormationDeployments.publishStackAssets (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:503:7)
    at CloudFormationDeployments.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:307:5)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:201:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:281:9)
Failed to publish one or more assets. See the error messages above for more information.
```
