### ISSUE TITLE
Environment variables not passed to docker build

### ISSUE THREAD

**Issue by MatthewSuntup** [pulumi/pulumi-docker#310]
## Issue details
When using the python function `pulumi_docker.Image()` and passing the `build` input as a `DockerBuildArgs`, the `env` argument is documented (https://www.pulumi.com/registry/packages/docker/api-docs/image/#dockerbuild) as:

>  Environment variables to set on the invocation of docker build, for example to support DOCKER_BUILDKIT=1 docker build.

However, the environment variables do not appear to get set.

### Steps to reproduce

- Python 3.9.5
- pulumi 3.16.0
- pulumi-docker 3.1.0

Provide the `env` argument to `pulumi_docker.DockerBuild()` which in turn is provided to `pulumi_docker.Image()`:
```python
image = pulumi_docker.Image(
    build=pulumi_docker.DockerBuild(env={"DOCKER_BUILDKIT": "1"}),
    ... # other arguments omitted
)
```

Expected: The resulting docker build should use Docker BuildKit
Actual: Docker BuildKit is not used (evident by the classic docker build output)

## Fix
I believe this issue is caused in[ line 658 of `pulumi-docker/docker.py`](https://github.com/pulumi/pulumi-docker/blob/0a6928ef65763f30820837d63d3ad9e59ad993e1/sdk/python/pulumi_docker/docker.py#L658):
```python
env = os.environ.copy().update(env)
```
The `update()` method modifies a dictionary and returns `None`. However, this line stores the return value from `update()` as `env` which is then used to set the environment variables (so no variables are ever set).

The simplest fix would be to change this line to:
```python
environ = os.environ.copy()
environ.update(env)
env = environ
```
I'll link a PR which makes this change.

**Comment by leezen** [comment]
Thank you for reporting, digging into it, and proposing a fix!

**Comment by tomryanx** [comment]
Is there a known workaround?

**Comment by MatthewSuntup** [comment]
> Is there a known workaround? 

Since `env` is always `None`, the current process' environment is inherited when `Popen()` is called:
> If env is not None, it must be a mapping that defines the environment variables for the new process; these are used instead of the default behavior of inheriting the current process’ environment.
\- https://docs.python.org/3/library/subprocess.html#subprocess.Popen

So one workaround is to set the environment variable in the current process before running Pulumi.

**Comment by tomryanx** [comment]
> So one workaround is to set the environment variable in the current process before running Pulumi.

I'm trying to inject things that aren't known advance, so this won't help me, unfortunately. Thanks anyway!

**Comment by MatthewSuntup** [comment]
> > So one workaround is to set the environment variable in the current process before running Pulumi.
> 
> I'm trying to inject things that aren't known advance, so this won't help me, unfortunately. Thanks anyway!

It might work to use `os.environ` to set the environment variable in the Pulumi script immediately before the call to `pulumi.docker.Image()`

**Comment by gshel** [comment]
+1

**Comment by advanderveer** [comment]
The same is true for the Go provider.
