### ISSUE TITLE
support of multi-architecture images?

### ISSUE THREAD

**Issue by Iced-Sun** [pulumi/pulumi-docker#317]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We are building multi-architecture EKS node groups. [EKS](https://docs.amazonaws.cn/en_us/eks/latest/userguide/eks-optimized-ami.html#arm-ami) requires docker manifests to support multi-architecture deployments. But I cannot find `@pulumi/docker` having the support of docker manifests.

Am I ignoring anything?

**Comment by leezen** [comment]
If you're using the `Image` resource, I believe there's an `extraOptions` parameter which will allow you to then provide the relevant flags (such as `--platform`)
