### ISSUE TITLE
 unexpected unknown property value for "registryServer"

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-docker#320]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
When I try to build a docker image with docker hub as registry (i did a `docker login` before), I get the error message:

```
 pulumi:pulumi:Stack (jetbrains-gateway-dev):
    error: program failed: waiting for RPCs: unexpected unknown property value for "registryServer"
    exit status 1

```

### Steps to reproduce
```go
_, err := docker.NewImage(ctx, "jetbrains-gateway", &docker.ImageArgs{
			Build: docker.DockerBuildArgs{
				Context: pulumi.String("./container"),
			},
			ImageName: pulumi.String("docker.io/user/iamge:1.0.0"),
		})
		if err != nil {
			return err
		}
```

Expected: no error message
Actual:  error message

**Comment by leezen** [comment]
This might be a bug where even though the argument is optional, the component is trying to set the output.

**Comment by HagaiBarel** [comment]
Seeing the same issue, also in `go`, `pulumi-docker` version `3.1.0`

**Comment by dirien** [comment]
Hi,

```
Registry:  docker.ImageRegistryArgs{},
```

Does the trick for me :)

**Comment by AaronFriel** [comment]
This issue should be resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)! See our blog post for more info: https://www.pulumi.com/blog/build-images-50x-faster-docker-v4/
