### ISSUE TITLE
Containers are recreated even though there are no changes in RemoteImage.Name

### ISSUE THREAD

**Issue by BeeHiveJava** [pulumi/pulumi-docker#325]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying to deploy a simple docker container with a prebuild image on a remote registry. Now this works, but Pulumi keeps detecting changes even though nothing has changed. When running `pulumi up --diff`, it shows that it detects the name as a `sha256` string, when instead it should've been just a regular name (see example below):

`~ image: "sha256:2cd4bc25ad14d7c652b17d49804dfb99a9ed702faa006ac2f9bdf72c8716a15d" => "traefik:v2.5.6"`

### Steps to reproduce

1. Use the following code:
```C#
var image = new RemoteImage("traefik", new RemoteImageArgs
{
    Name = "traefik:v2.5.6",
    KeepLocally = true
});
        
var container = new Container("traefik", new ContainerArgs
{
    Name = "traefik",
    Image = image.Name
});
```

2. Run pulumi up: `pulumi up --diff`
3. Run pulumi up: `pulumi up --diff`

Expected: I expected the second run (step 3) to have no changes.
Actual: I observe a change in name (`~ image: "sha256:2cd4bc25ad14d7c652b17d49804dfb99a9ed702faa006ac2f9bdf72c8716a15d" => "traefik:v2.5.6"`) and Pulumi recreates the container.

**Comment by BeeHiveJava** [comment]
I'd like to note that using `image.Latest` works, of course. But I'd prefer not to refer to a sha hash, but rather the image directly. And more importantly, that property is deprecated according to https://www.pulumi.com/registry/packages/docker/api-docs/remoteimage. The suggest alternative `image.RepoDigest` produces the same result as in my issue: `~ image: "sha256:2cd4bc25ad14d7c652b17d49804dfb99a9ed702faa006ac2f9bdf72c8716a15d" => "traefik@sha256:2f603f8d3abe1dd3a4eb28960c55506be48293b41ea2c6ed4a4297c851a57a05"`.

**Comment by mountainpath9** [comment]
I was assuming the version 4 of the provider would address this. But the issue remains.

**Comment by mountainpath9** [comment]
It seems that the `imageId` property of `RemoteImage` has the desired behaviour here. See https://github.com/pulumi/pulumi-docker/issues/564

**Comment by guineveresaenger** [comment]
Thank you for following up here, @mountainpath9 - I will close this issue for now. Feel free to reopen if necessary. 🙏
