### ISSUE TITLE
Docker Image resource randomly failing with Error saving credentials

### ISSUE THREAD

**Issue by CezaryKlus** [pulumi/pulumi-docker#326]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

A Pulumi stack containing docker resource randomly fails on `pulumi up` and performing stack update:

```
error: Error saving credentials: rename C:\Users\   \.docker\config.json592651639 C:\Users\    \.docker\config.json: Access is denied.
    error: Pulumi.ResourceException: ' docker login' failed with exit code 1

       at async Task<string> Pulumi.Docker.Docker.RunCommandThatMustSucceed(string cmd, string[] args, Resource logResource, bool reportFullCommandLine, string stdin, ImmutableDictionary<string, string> env)
       at async Task Pulumi.Docker.Docker.LoginToRegistry(ImageRegistryUnwrap registry, Resource logResource)+(?) => { }
````

Platform: Windows 10
Backend: Azure Blob Storage

### Steps to reproduce
1. Prepare a Pulumi stack with docker Image resource dependency
2. Run `pulumi up`

Expected:

Assuming code and docker resources are fine command shall always succeed.

Actual:

Occasionally command fails with the error as above. Running command with elevated permissions does not really help. Rerunning `pulumi up` helps - it may be related to closing other instances of Powershell/CMD with previous runs of pulumi up.
Is this related to any locks acquired by e.g. other terminals where `pulumi up` was run?

**Comment by badokun** [comment]
I'm seeing the same thing when building multiple images (c# solution). I tried adding a lock around that piece of code, since it seems to have contention, but no luck

```csharp
    public Image Build(string appName, string imageBaseName, string context)
    {
        lock (lockObject)
        {
            var imageName = Output.Format($"{_registryServer}/{imageBaseName}");
            var image = new Image($"{appName}-image", new ImageArgs
            {
                Build = new DockerBuild { Context = context },
                ImageName = imageName,
                Registry = new ImageRegistry
                {
                    Server = _registryServer,
                    Username = _registryUsername,
                    Password = _registryPassword
                },
            });
            return image;
        }
    }
```

**Comment by CezaryKlus** [comment]
I was trying cross thread synchronization via SemaphoreSlim but due to the architecture of the Pulumi itself nothing really helps from the top level stack code. 
The issue is at: https://github.com/pulumi/pulumi-docker/blob/1e928a9eed9279a021515269c7ce372504f32d97/sdk/dotnet/Docker.cs#L440
The fix should focus on isolating a process of building and pushing an image somehow....

**Comment by alecor191** [comment]
I'm hitting the same issue: `pulumi up` on a stack with more than one Docker Image build results in the `Error saving credentials` error mentioned above. 

With 2 images in the stack I got it from time to time, with 4 images I get it pretty much 100% of the time on at least one of the images.

As a workaround I tried to (mis)use `DependsOn` and have Image 1 depend on Image 2, Image 2 depend on Image 3, etc. as I thought that would force sequential execution and hopefully mitigate the issue. However, I'm still hitting the issue mentioned above.

Is there an ETA for addressing this? Or is there a workaround we could use in the meantime?

### Additional information

- I'm on Windows 10
- Using Pulumi with C#
- Pulumi version: v3.28.0
- Image is pushed to Azure ACR

**Comment by AaronFriel** [comment]
This issue should be resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)! See our blog post for more info: https://www.pulumi.com/blog/build-images-50x-faster-docker-v4/
