### ISSUE TITLE
getRegistryImage is rejected by ghcr.io for private docker images

### ISSUE THREAD

**Issue by alexanderniebuhr** [pulumi/pulumi-docker#332]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Using the upstream terraform provider, leads to have the same issues in pulumi as well.

It seams that the provider uses basic http auth instead of bearer token based authentication,
therefore all calls fail with an `403 Forbidden`

See this Issue as an upstream track of https://github.com/kreuzwerker/terraform-provider-docker/issues/334, so once that lands, the terraform-provider-docker should get upgraded, to mitigate this downstream.

### Steps to reproduce

1. publish private docker image on GitHub
2. make an provider with the ghcr.io registry, username & PAT as password
3. use getRegistryImage() on the image in the registry
4. try to get the digest

Expected: `Output<getRegistryImageResult>`
Actual: 
```
Got error when attempting to fetch image version xyz/xyz:latest from registry: Got bad response from registry: 403 Forbidden
```

P.S.: If there is an way to include a workaround in the meantime, I would love to see that.

**Comment by stakauskas** [comment]
Facing exact same issue. Auth works with: `docker.RemoteImage` for pulling images, but fails for reading metadata with: `docker.getRegistryImage` with the above error.

**Comment by stack72** [comment]
This was closed out upstream so I can close it here :)

**Comment by siikanen** [comment]
Hello! Seems like this is still an issue in the upstream and should be reopened. See [https://github.com/kreuzwerker/terraform-provider-docker/issues/593](https://github.com/kreuzwerker/terraform-provider-docker/issues/593).

I faced this exact same issue when trying to use pulumi to distribute private images. Pulling image works just fine with `dockr pull <myimage>` but Pulumi is unable to check images metadata using `docker.getRegistryImage`.

Steps to reproduce:

```

// This will work with any public docker image, but fail with private one  

import * as pulumi from "@pulumi/pulumi";
import * as docker from "@pulumi/docker";

const ubuntu = docker.getRegistryImage({
    name: "ubuntu:precise", // Replace this with private image.
});
const ubuntuRemoteImage = new docker.RemoteImage("ubuntu", {
    name: ubuntu.then(ubuntu => ubuntu.name),
    pullTriggers: [ubuntu.then(ubuntu => ubuntu.sha256Digest)],
});
```

**Comment by piccolobeerus** [comment]
The best way to go about this, is switch to CDKTF+TypeScript, Pulumi has too many bugs which they like to close prematurely.
