### ISSUE TITLE
"Too many list items" when more than one registryAuth entry in provider

### ISSUE THREAD

**Issue by rafalkrupinski** [pulumi/pulumi-docker#339]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When creating docker.Provider with two registryAuth elements, pulumi up fails with error message:
```
docker:index:RemoteImage (mongo):
    error: could not validate provider configuration: 1 error occurred:
        * Too many list items: Attribute supports 1 item maximum, but config has 2 declared.
```

**Comment by viveklak** [comment]
@rafalkrupinski what version of the provider are you running with? I believe this was fixed in https://github.com/pulumi/pulumi-docker/pull/306/files (v3.1.0).

**Comment by AaronFriel** [comment]
@rafalkrupinski can you provide a minimal program to reproduce? I'm not sure if this is the case any longer - we've updated to a much newer version of the upstream provider since.

**Comment by AaronFriel** [comment]
Sorry to hear that; I'll close the issue accordingly.
