### ISSUE TITLE
RemoteImage unable to pull from private registry

### ISSUE THREAD

**Issue by 1Four1Two** [pulumi/pulumi-docker#356]
Whenever I try to use remoteimage to get a container from my private registry I get a access denied message

Unable to read Docker image into resource: unable to pull image XXXXXXXX/XXXXXXXXXXX: error pulling image XXXXXXXX/XXXXXXXXXXX: Error response from daemon: pull access denied for XXXXXXXX/XXXXXXXXXXX, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by AMKamel** [comment]
I am facing the same issue with private repo on official docker hub

**Comment by 1Four1Two** [comment]
Found a workaround for this issue. 

if you add "docker.io/" to the beginning of the container name that you want to pull then it seems to work

ie docker.io/<privatereponame>/<imagename>:<tags>

**Comment by lblackstone** [comment]
It looks like this was an issue with the client configuration, so I'll close this out.
