### ISSUE TITLE
`Image` doesn't support target stage selection

### ISSUE THREAD

**Issue by connorbrinton** [pulumi/pulumi-docker#37]
The constructor of `image.Image` does not support specifying a target stage to build from the Dockerfile. Here's an example multi-stage Dockerfile:
```
FROM python:3.6 AS base

FROM base AS dependencies
RUN pip install gunicorn

FROM dependencies AS release
CMD ["gunicorn", "wsgiref.simple_server:demo_app"]

FROM dependencies AS test
RUN pip install pytest
COPY tests/ tests/
CMD ["pytest"]
```

One would build the release image by executing `docker build --target=release .` and the test image by executing `docker build --target=test .`.

Pulumi has some awareness of how to build specific stages, but does not expose this ability through `image.Image`. The current constructor of `image.Image` is:
```
constructor(name: string, args: ImageArgs, opts?: pulumi.ComponentResourceOptions)
```

I propose that `target` be added either as a new key of the `ImageArgs` interface or as a new optional argument to the constructor. That would be very useful to me, and hopefully other people.

**Comment by lukehoban** [comment]
Good suggestion. This should fit well as an extension of the rent API design.

**Comment by stack72** [comment]
Hi @connorbrinton 

My most sincere apologies that there hasn't been any movement on this issue for such a long time. This is something we are trying to get better at.

I have just pushed an example that will allow you to do this. To use it, the code would look as follows:

```
import * as docker from "@pulumi/docker";

const myDependenciesImage = new docker.Image("my-image", {
    imageName: "pulumi-user/example:v1.0.0",
    build: {
        target: "dependencies",
    },
    skipPush: true,
});

export const depsImage = myDependenciesImage.imageName;
```

Notice that I am using the build argument - this is an object that has a new parameter added, called "target" this will then append ``--target=argValue` to the  docker build command

Hope this helps

Paul

**Comment by connorbrinton** [comment]
No worries, thanks for the PR and example Paul! 😄
