### ISSUE TITLE
Wrong Go data type reference

### ISSUE THREAD

**Issue by pasdam** [pulumi/pulumi-docker#375]
File: [themes/default/content/registry/packages/docker/api-docs/getregistryimage/_index.md](https://www.pulumi.com/registry/packages/docker/api-docs/getregistryimage/)

In the go code snippet
```diff
- ubuntuRegistryImage, err := docker.LookupRegistryImage(ctx, &GetRegistryImageArgs{
+ ubuntuRegistryImage, err := docker.LookupRegistryImage(ctx, &docker.LookupRegistryImageArgs{
```

**Comment by stack72** [comment]
Closing this as a duplicate of the related bug https://github.com/pulumi/pulumi/issues/10309
