### ISSUE TITLE
Option to disable docker push for image with SHA digest in tag.

### ISSUE THREAD

**Issue by eliskovets** [pulumi/pulumi-docker#378]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
It would be nice to have an option to disable push for image_id tagged images and push only image with tag requested in image_name. 

We use ECR for our internal docker images and our default policy is to delete any untagged image older than N days. 
Pulumi pushes digest as a part of the tag for docker image, so our policy doesn't work for the images pushed by pulumi. 
It would be nice to have an option to disable push for image tagged by SHA digest.

### Affected area/feature
https://github.com/pulumi/pulumi-docker/blob/fa0159258e220cefa6a93d1e1f77676641721365/sdk/python/pulumi_docker/docker.py#L272

**Comment by stack72** [comment]
Hi @eliskovets 

We are looking at how to best rework the docker.py set of our SDK so we will ensure that this is looked at as part of that work

Paul

**Comment by AaronFriel** [comment]
This issue should be resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)! See our blog post for more info: https://www.pulumi.com/blog/build-images-50x-faster-docker-v4/
