### ISSUE TITLE
Link to java package missing from README

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi-docker#383]
The other language have links to their packages for this provider. Java is missing from README though, I think the right link is https://search.maven.org/artifact/com.pulumi/docker

**Comment by nagkumar** [comment]
Yes, the web view URL is  https://www.pulumi.com/registry/packages/docker/

no java here.. 
![image](https://user-images.githubusercontent.com/332234/185127887-28137cd5-9e98-4d05-9bb7-3d6f600cdc2e.png)

**Comment by AaronFriel** [comment]
Looks like this is still an issue in v4.
