### ISSUE TITLE
Docker external / persistent volume

### ISSUE THREAD

**Issue by AlexAndrascu** [pulumi/pulumi-docker#389]
Hello!

I'm trying to create a container with an external named volume or otherwise a volume that doesn't get deleted / removed when tearing down the stack with `pulumi down`.

Coming from a docker-compose mindset I'm probably either trying to do something in an awkward or perhaps the wrong way.  

I can see there are various resources, properties and inputs such as `volumes` , `mounts` (with [ContainerMountArgs[]](https://www.pulumi.com/registry/packages/docker/api-docs/container/#containermount)) which should in theory make this possible (I also did try some), but really struggling to put it together or find an example, reference or docs on how to make it work.

Take this for example which works fine:
```
const graylogdata = new docker.Volume("graylog_data", {});

const graylogContainer = new docker.Container("graylog", {
    image: graylogImage.name,
    volumes: [
        {
            volumeName: graylogdata.name,
            containerPath: '/usr/share/graylog/data',
        },
    ],
    entrypoints: [
        "/docker-entrypoint.sh"
    ],
    networksAdvanced: [
        { name: network.name, aliases: ["graylog"] },
    ],
    ports: [{
        internal: 9000,
        external: 9000
    }],
    restart: "unless-stopped",
});
```
How would I keep the graylogdata volume to re-attach it the next time a stack is created? Would this be possible at all? 
Many thanks!

**Comment by AlexAndrascu** [comment]
Ok, so I've managed to achieve this by creating the volume with:

`docker create volume graylog_data` then

importing with

`pulumi import docker:index/volume:Volume graylog_data graylog_data` 
(note that the documentation is mentioning about an id but in reality there's no id for local driver volumes just a regular name)

which in turn generated the code needed for the script:

```
const gray_logdata = new docker.Volume("graylog_data", {
    driver: "local",
    name: "graylog_data",
}, {
    protect: true,
});
``` 
This works. However, now `pulumi down` complains at preview stage about:

```
Diagnostics:
  docker:index:Volume (graylog_data):
    error: Preview failed: unable to delete resource "urn:pulumi:dev::opnmon::docker:index/volume:Volume::graylog_data"
    as it is currently marked for protection. To unprotect the resource, either remove the `protect` flag from the resource in your Pulumi program and run `pulumi up` or use the command:
    `pulumi state unprotect 'urn:pulumi:dev::opnmon::docker:index/volume:Volume::graylog_data'`
 
  pulumi:pulumi:Stack (opnmon-dev):
    error: preview failed
```
It does work if I pass the -f param like `pulumi down -f` but this doesn't seem right. Is there a better way to do this?

**Comment by stack72** [comment]
Hi @AlexAndrascu 

If you are running a pulumi destroy operation then it will try and delete everything in the stack. What I would suggest here is to use a stack reference and manage your docker volumes in a different project. Then export their names and be able to attach them

https://www.pulumi.com/docs/intro/concepts/stack/#stackreferences

This means that they won't be destroyed in a pulumi destroy operation on your containers project

Paul

**Comment by AlexAndrascu** [comment]
Thank you for the answer!
