### ISSUE TITLE
[spike] `Image`: Implement a selection of `extraOptions`

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-docker#424]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In v3.x.x, we allow users to set [extra options](https://www.pulumi.com/registry/packages/docker/api-docs/image/#extraoptions_nodejs) which get passed to the Docker provider as command line flags.

Using the client, these all have to be implemented separately.

- Determine which options users are currently relying on
- Add logic to capture and parse `extraOptions`
    - Add new fields to the schema rather than a grab bag list
    - Deprecate the `extraOptions` field
- Pass on options to the client

**Comment by LouisAmon** [comment]
As mentionned [here](https://github.com/pulumi/pulumi-docker/issues/436#issuecomment-1468522570), I do believe that implementing `CacheTo` would be immensely helpful to people that want to leverage the GitHub Actions Cache

https://docs.docker.com/build/cache/backends/gha/

**Comment by uatach** [comment]
I think the `--network` flag would be great.

In GCP Cloud Build we need access to the `cloudbuild` network to fetch credentials, there's currently an open issue about it in the [Google IssueTracker](https://issuetracker.google.com/issues/227640666) and some discussions of workarounds for BuildKit in https://github.com/docker/buildx/issues/175

**Comment by AaronFriel** [comment]
In #549 a user requested the build use multiple tags and push each of them.

**Comment by AaronFriel** [comment]
In #539 a user requested the `--secret` option.

**Comment by LouisAmon** [comment]
The `--ssh` is currently missing and preventing us from migrating into pulumi-docker 4.x

We use it to clone a GitHub repo inside our Dockerfile (the SSH key is the main means of authentication with GH)

**Comment by JohnMcGue** [comment]
> 

bump on this. our current image build:

`const uploaderImage = registryInfo.apply((registryInfo) => new docker.Image(uploaderImageName, {
    build: {
        context: "../uploader",
        // needed for ssh install of our private repo
        extraOptions: [
            '--ssh', `default=/home/runner/.ssh/id_ed25519`,
        ],
        env: {
            DOCKER_BUILDKIT: "1",
        },
    },
    imageName: pulumi.interpolate`${ecrRepo.repositoryUrl}:${imageName}`,
    registry: registryInfo,
}));
`
we are also using the SSH key to authenticate with a private GitHub repository. this is blocking us from migrating to 4.x.

**Comment by yoanisgil** [comment]
Not having the ability to pass build secrets is really a major drawback for us for moving with the new Docker provider (which means that I have to add a step in my CI/CD to build the image ...)

**Comment by mpuhacz** [comment]
Same problem as @JohnMcGue. This is a blocker for migration.

**Comment by guineveresaenger** [comment]
@LouisAmon @JohnMcGue @mpuhacz - I'm not sure if this is useful for your particular situations, but you should be able to use `sshOpts` with an explicit provider: https://www.pulumi.com/registry/packages/docker/api-docs/provider/#sshopts_nodejs.

**Comment by rtrindvg** [comment]
Is there any option for the quiet parameter? The verbosity on our processes are generating some collateral effects we could avoid otherwise.

**Comment by AaronFriel** [comment]
@rtrindvg Are you using Docker v4.x or v3.x?

**Comment by rtrindvg** [comment]
> @rtrindvg Are you using Docker v4.x or v3.x?

I was using v3.x before, using the quiet parameter on the extraOptions. Now we transitioned to v4.x, because we had an issue of generating a new docker image on every preview, which was slowing down the process, but I see no corresponding way of generating the image without a very large output in some complex building process.

**Comment by AaronFriel** [comment]
With v4, you should no longer see a "very large output", do you have an example you can share of a Dockerfile & Pulumi program that produces said output?

**Comment by AaronFriel** [comment]
> I could reproduce the issue using a simple repository, and also how there are different behavior when using CLI versus the pulumi/actions github CI module.

Definitely, this seems like a feature request for the Pulumi CLI, as it looks like different types of events are logged with `--diff` depending on whether it's a pty or not. Please open an issue here on  http://github.com/pulumi/pulumi!

If you're able to look into using the Pulumi Cloud backend, you'll see that by integrating with the Pulumi engine, we can toggle between toggle between verbose, diff and diagnostic outputs. Here's what that looks like:
![image](https://github.com/pulumi/pulumi-docker/assets/788800/eca2a34f-b315-44c1-b397-7dd8338ef4d9)

Where selecting "Diff" or "Diagnostic" will provide more verbose output, which I think matches what you're seeing.

**Comment by rtrindvg** [comment]
Thanks, will open the issue there.
Unfortunately Pulumi Cloud backend is outside of our budget for now, but it would be perfect, for sure. 
Thanks for the feedback!

**Comment by blampe** [comment]
Hi folks, we just released a new Docker Build provider focused exclusively on building images with buildx/BuildKit. It provides `--ssh`, `--cache-to`, multiple tags, and quieter logs out of the box. We recommend you use it for building images going forward. Please take a look and give us feedback!

The repository is [here](https://github.com/pulumi/pulumi-docker-build); our blog announcement is [here](https://www.pulumi.com/blog/docker-build/); and finally API docs are [here](https://www.pulumi.com/registry/packages/docker-build/) along with examples of how to migrate your existing `Image` resources to `dockerbuild.Image`.

We won't be able to add this functionality in this provider for a number of reasons, so I'm closing this as wont-fix.
