### ISSUE TITLE
Need adequate test-suite for pulumi-docker package/repo

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-docker#43]
We need to build up a reasonable set of unit tests for this package/repo.  These tests need to be able to cover both the core docker/image cases, as well reasonable coverage of the knobs we allow in these APIs.

Ideally, these tests can run against docker-hub, and can also be run by contributors locally with their own docker credentials.

**Comment by lukehoban** [comment]
This is important - but given that we moved all the user-facing work in this package back to M22, I think we should move this there as well and make sure we can get this done as part of the major user-facing improvements we need to make in this package.  Would love to land key improvements to test coverage here early to help us grow confidence in other changes we need to make here.

**Comment by AaronFriel** [comment]
We've added additional tests with v4 to cover important registry & Image resource use cases.
