### ISSUE TITLE
RemoteImage vs Azure WebApp

### ISSUE THREAD

**Issue by simra** [pulumi/pulumi-docker#448]
### What happened?

Deploying a RemoteImage to an azure WebApp omits required registry settings.

### Steps to reproduce

1. Define a remote image from dockerhub, eg:
```

rabbitmq_image = docker.RemoteImage(
    "rabbitmq",
    name="rabbitmq:3.8.9-management",
)

```
2. Attempt to deploy the image to an azure webapp.  Azure requires a registry definition, even if it's docker hub, so the deployment provisions the app but never pulls the image.  My code is below. 

![image](https://user-images.githubusercontent.com/2946735/210046632-0753b4c0-72f6-475f-ab0c-531f46a96552.png)

```

rabbitmq_appservice = web.WebApp(
    "rabbitmq-appservice",
    name=rabbitmq_name,
    resource_group_name=resource_group.name,
    location=resource_group.location,
    server_farm_id=rabbitmq_appserviceplan.id,
    site_config=web.SiteConfigArgs(
        linux_fx_version=rabbitmq_image.name.apply(lambda name: f"DOCKER|{name}"),
        app_settings=[
                web.NameValuePairArgs(
                    name="RABBITMQ_DEFAULT_USER",
                    value="guest"
                )             
            ],
    ),
)
```

### Expected Behavior

I expected the deployment to resolve the remote image and pull it.

### Actual Behavior

The webapp is stubbed out in azure but the image is never pulled.

### Output of `pulumi about`

CLI
Version      3.50.2
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.10.0
azure-native  1.90.0
docker        3.1.0
python        unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable='/home/simra/t4t-infrastructure/annotation_api/venv/bin/python3' version='3.8.15
'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/simra
User           simra
Organizations  simra, tech4tracing

Dependencies:
NAME                 VERSION
pip                  22.3.1
pre-commit           2.21.0
pulumi-azure         5.10.0
pulumi-azure-native  1.90.0
pulumi-docker        3.1.0
wheel                0.38.4

### Additional context

Maybe I'm setting up the remote image incorrectly?  The API doesn't seem to have any provisions for specifying the registry.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @simra, your version of pulumi-docker is over a year old. Are you able to upgrade and try again?

**Comment by mikhailshilkov** [comment]
Since we haven't heard back, I'll go ahead and close this issue as stale. Also, it seems more of an Azure question than a Pulumi Docker provider question. Please open a new issue if the problem still persists and provide the details for us to reproduce it. Thank you!
