### ISSUE TITLE
Docker Tag Fails

### ISSUE THREAD

**Issue by jdmaguire** [pulumi/pulumi-docker#451]
### What happened?

When trying to build a docker image as part of my pulumi program, subsequent runs fail because `docker tag <thing> <thing>:<tag>` fails with "already exists".

### Steps to reproduce

I have an index.ts file like this:

```
import * as docker from "@pulumi/docker";

const x = "jdmaguire";
const image = new docker.Image("image", {
  imageName: `${x}`,
  build: {
    context: ".",
    dockerfile: "./Dockerfile",
    env: {
    },
  },
  registry: {
    server: "docker.io",
    username: x,
    password: "<key>",
  },
});
```

My Dockerfile looks like this:

```
FROM alpine:latest
```

package.json is:

```
{
    "name": "pushing",
    "main": "index.ts",
    "devDependencies": {
        "@types/node": "^14"
    },
    "dependencies": {
        "@pulumi/docker": "^3.6.1",
        "@pulumi/pulumi": "^3.0.0"
    }
}
```

tsconfig.json is:

```
{
    "compilerOptions": {
        "strict": true,
        "outDir": "bin",
        "target": "es2016",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "experimentalDecorators": true,
        "pretty": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitReturns": true,
        "forceConsistentCasingInFileNames": true
    },
    "files": [
        "index.ts"
    ]
}
```

I then run `pulumi up -v=3`

### Expected Behavior

The second time I run `pulumi up -v=3`, it should succeed.

### Actual Behavior

It fails:

```
> $ pulumi up -v=3
Previewing update (dev)

View Live: https://app.pulumi.com/jdmaguire/pushing/dev/previews/0497e248-ff4b-401d-8161-96dd5408203b

     Type                   Name                 Plan       Info
     pulumi:pulumi:Stack    pushing-dev                     
     ├─ docker:image:Image  image                           1 warning
 -   └─ docker:image:Image  gke-bootstrap-image  delete     


Diagnostics:
  docker:image:Image (image):
    warning: #1 [internal] load .dockerignore
    #1 sha256:f985e14d06051a0bc9228dfb8946b05aff01cb5c7c0673fb0cd8c189753d0245
    #1 transferring context: 2B done
    #1 DONE 0.0s
    
    #2 [internal] load build definition from Dockerfile
    #2 sha256:33ca39a44052c11bd1bbe763ebd4db2498d62a56387f236f3f63489fecf92ac0
    #2 transferring dockerfile: 73B done
    #2 DONE 0.0s
    
    #3 [internal] load metadata for docker.io/hashicorp/terraform:1.3.3
    #3 sha256:131bc2cd2bd7506cb8b6425837840384ade28714cf4abacb3ad57c1e682946a9
    #3 DONE 0.6s
    
    #4 [1/1] FROM docker.io/hashicorp/terraform:1.3.3@sha256:d97b8378e608a994196302e1e4b386b94d229de1bc7c514a3169d66c53b4e13e
    #4 sha256:2611ec3cf36a097d4390bb20cce2f0bae6a48ae1f41db84c61f847a9fa13f8e5
    #4 resolve docker.io/hashicorp/terraform:1.3.3@sha256:d97b8378e608a994196302e1e4b386b94d229de1bc7c514a3169d66c53b4e13e 0.0s done
    #4 CACHED
    
    #5 exporting to image
    #5 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
    #5 exporting layers done
    #5 exporting manifest sha256:75de258d911eefbfd15b6c400cae719de529b71f2b7b3428c666caf15e0a4cda done
    #5 exporting config sha256:f087271b386fc8fd5766202d24b8575b50671542cd6a49520710fda2cfd94f27 done
    #5 naming to docker.io/library/jdmaguire:latest done
    #5 unpacking to docker.io/library/jdmaguire:latest done
    #5 DONE 0.0s
    
    Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them


Do you want to perform this update? yes
Updating (dev)

View Live: https://app.pulumi.com/jdmaguire/pushing/dev/updates/39

     Type                   Name         Status         Info
     pulumi:pulumi:Stack    pushing-dev  **failed**     1 error
     └─ docker:image:Image  image        **failed**     1 error; 2 warnings


Diagnostics:
  pulumi:pulumi:Stack (pushing-dev):
    error: Error: ' docker tag jdmaguire jdmaguire:75de258d911eefbfd15b6c400cae719de529b71f2b7b3428c666caf15e0a4cda' failed with exit code 1
    
        at /Users/maguij1/Desktop/work/src/github.com/streamnative/scratch/pushing/node_modules/@pulumi/docker.ts:592:15
        at Generator.next (<anonymous>)
        at fulfilled (/Users/maguij1/Desktop/work/src/github.com/streamnative/scratch/pushing/node_modules/@pulumi/docker/docker.js:18:58)

  docker:image:Image (image):
    warning: 
    Logging in with your password grants your terminal complete access to your account.
    For better security, log in with a limited-privilege personal access token. Learn more at https://docs.docker.com/go/access-tokens/

    warning: #2 [internal] load build definition from Dockerfile
    #2 sha256:73c82a0a6c4c9283c11250407390b51b255bae5b39d22b83d1723002e2f9b18f
    #2 transferring dockerfile: 73B done
    #2 DONE 0.0s
    
    #1 [internal] load .dockerignore
    #1 sha256:c2fdd5435a40ad5ee4640e1e0dab4c5b7610cdd83f1974d4a4e75e7dc0194c65
    #1 transferring context: 2B done
    #1 DONE 0.0s
    
    #3 [internal] load metadata for docker.io/hashicorp/terraform:1.3.3
    #3 sha256:131bc2cd2bd7506cb8b6425837840384ade28714cf4abacb3ad57c1e682946a9
    #3 DONE 0.4s
    
    #4 [1/1] FROM docker.io/hashicorp/terraform:1.3.3@sha256:d97b8378e608a994196302e1e4b386b94d229de1bc7c514a3169d66c53b4e13e
    #4 sha256:2611ec3cf36a097d4390bb20cce2f0bae6a48ae1f41db84c61f847a9fa13f8e5
    #4 resolve docker.io/hashicorp/terraform:1.3.3@sha256:d97b8378e608a994196302e1e4b386b94d229de1bc7c514a3169d66c53b4e13e 0.0s done
    #4 CACHED
    
    #5 exporting to image
    #5 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
    #5 exporting layers done
    #5 exporting manifest sha256:75de258d911eefbfd15b6c400cae719de529b71f2b7b3428c666caf15e0a4cda done
    #5 exporting config sha256:f087271b386fc8fd5766202d24b8575b50671542cd6a49520710fda2cfd94f27 done
    #5 naming to docker.io/library/jdmaguire:latest done
    #5 unpacking to docker.io/library/jdmaguire:latest done
    #5 DONE 0.0s
    
    Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

    error: Error response from daemon: image "docker.io/library/jdmaguire:75de258d911eefbfd15b6c400cae719de529b71f2b7b3428c666caf15e0a4cda": already exists

Resources:
    2 unchanged

Duration: 3s

warning: A new version of Pulumi is available. To upgrade from version '3.47.2' to '3.50.2', run 
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Output of `pulumi about`

CLI          
Version      3.47.2
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  12.6.1
Arch     arm64

This project is written in nodejs: executable='/Users/maguij1/.asdf/shims/node' version='v18.2.0'

Current Stack: dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::pushing::pulumi:pulumi:Stack::pushing-dev
docker:image:Image   urn:pulumi:dev::pushing::docker:image:Image::gke-bootstrap-image

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jdmaguire
User           jdmaguire
Organizations  jdmaguire, streamnative

Dependencies:
NAME            VERSION
@pulumi/docker  3.6.1
@pulumi/pulumi  3.51.0
@types/node     14.18.36

Pulumi locates its logs in /var/folders/pr/4j3s6b0n7fdgjnglbwvfw8jc0000gn/T/ by default
warning: A new version of Pulumi is available. To upgrade from version '3.47.2' to '3.50.2', run 
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

### Additional context

I'm wondering Docker 22.06, Mac OS 12.6.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jdmaguire** [comment]
Looking into this slightly more (I have a few different machines running a few different versions of docker), I only get this issue with Docker Version 22.06+ using API version 1.43+

**Comment by thomas11** [comment]
Hi @jdmaguire, thanks for the report! What are some Docker and API versions you have observed succeeding?

**Comment by jdmaguire** [comment]
Basically, anything below Docker engine version 22.x and API version 1.43 works from my observations.

One thing I noticed today, the machines I'm I'm getting this issue on are running Docker Desktop with engine version 22.06.0-beta.0-902-g2708be0db4.m, API 1.43, and containerd (this is an option on Docker Desktop). Containerd is where this issue is coming from. Containerd does not overwrite tags by default. Docker which always allows it.

**Comment by guineveresaenger** [comment]
hi @jdmaguire - thank you for doing a deep dive on this and pinpointing containerd image store as the cause. Could you clarify whether this happens:

a) any setting where containerd image storage is enabled
b) only on some engine versions (but others work, even if containerd image storage is enabled)

Also - do you happen to know if it is possible to toggle the default to _allow_ overwriting tags to containerd image store?

Catching this use case, either via issuing a warning instead of failing on `pulumi up`, or by allowing an override, would be a new feature request.
At first glance, there seems to currently not be a way to use the the Docker CLI or the SDK to enable the containerd image storage, _or_ override its tagging response, so unfortunately I don't think there's any workaround CLI flags you could pass to the provider at this moment.

**Comment by jdmaguire** [comment]
> At first glance, there seems to currently not be a way to use the the Docker CLI or the SDK to enable the containerd image storage, or override its tagging response, so unfortunately I don't think there's any workaround CLI flags you could pass to the provider at this moment.

That's my understanding too.

There is nothing to do here in this library. I'll close this issue. Thanks for your patience.

I wrote a little 'bug' report to Docker about this oddity. Containerd image storage for docker is a beta feature. If and when they do use containerd by default for image storage, I'm sure they'll have this discrepancy either fixed or have flags to harmonize the difference.

(For anyone who falls into the same issue as me, the workaround is to [disable containerd for image storage.](https://docs.docker.com/desktop/containerd/). For the time being, it is disabled by default.)
