### ISSUE TITLE
Provider configuration Error

### ISSUE THREAD

**Issue by 1Four1Two** [pulumi/pulumi-docker#456]
### What happened?

After upgrading to 3.6.1 I get the following error. There have been no code changes apart from the version upgrade

    error: could not validate provider configuration: 1 error occurred:
        * Attribute must be a single value, not a map

Rolling back to 3.6.0 fixes the error

### Steps to reproduce

Create a provider and add it to a resource ie an Image

### Expected Behavior

to be able to create a provider and attach it to a resaourceresource

### Actual Behavior

    error: could not validate provider configuration: 1 error occurred:
        * Attribute must be a single value, not a map

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
hi @1Four1Two - I cannot reproduce this behavior without more context. Can you share a code snippet?

**Comment by 1Four1Two** [comment]
@guineveresaenger 
This is how I am creating the provider

        private static Provider createProvider(string name, Output<string> address, Output<string> username, Output<string> password,
            Output<string>? host, Resource? resource)
        {
            var auths = getRegistryAuthArgsList(address, username, password);
            var providerArgs = getProviderArgs(auths, host);

            if (resource == null) return new Provider(name, providerArgs);

            var resourceList = CustomResourceOption.CreateResourceList();
            resourceList.Add(resource);

            return new Provider(name, providerArgs, new CustomResourceOptions { DependsOn = resourceList });
        }


        private static List<ProviderRegistryAuthArgs> getRegistryAuthArgsList(Output<string> address, Output<string> username, Output<string> password)
        {
            var providerRegistryAuthArgs = getProviderRegistryAuthArgs(address, username, password);

            return new List<ProviderRegistryAuthArgs>
            {
                providerRegistryAuthArgs,
            };
        }


        private static ProviderRegistryAuthArgs getProviderRegistryAuthArgs(Output<string> address, Output<string> username, Output<string> password)
        {
            return new ProviderRegistryAuthArgs
            {
                Address = address,
                Username = username,
                Password = password
            };
        }

        private static ProviderArgs getProviderArgs(List<ProviderRegistryAuthArgs> auths, Output<string>? host)
        {
            return new ProviderArgs
            {
                RegistryAuth = auths,
                Host = host!,
            };
        }

Then I attach it to the Custom resource like this
    public void CreateProviderResourceOptions()
    {
        ProviderCustomResourceOptions = new CustomResourceOptions
        { DependsOn = Provider, Provider = Provider, Parent = Provider };
    }

Then add it to the resource I am creating
var network = Network.Get("default", networkId, options: ProviderCustomResourceOptions);

**Comment by 1Four1Two** [comment]
Pulumi 3.50.0
Pulumi Docker 3.6.0

If I go above thee versions I get the problem

**Comment by 1Four1Two** [comment]
it has docker in the name of the project. Would that be a problem?

**Comment by Megasware128** [comment]
This is still a problem without docker in the name.
![image](https://user-images.githubusercontent.com/3170510/224735410-495d7a16-2cf1-471e-8c60-f279cde88b81.png)
![image](https://user-images.githubusercontent.com/3170510/224735496-bb89e8cc-9163-4201-9491-29e0122ac1a2.png)
![image](https://user-images.githubusercontent.com/3170510/224735790-1d83911c-023d-4fee-89cc-f8ad8e2d57bf.png)
