### ISSUE TITLE
Docker credentials are cached indefinitely

### ISSUE THREAD

**Issue by dferretti** [pulumi/pulumi-docker#459]
### What happened?

I am using the C# Automation API in a long-running background worker and finding my AWS ECR auth tokens are expiring.

I think this is the culprit: https://github.com/pulumi/pulumi-docker/blob/v3.6.1/sdk/dotnet/Docker.cs#L446

### Steps to reproduce

I create an ECR repo and docker image similar to the following:
```c#
var repo = new Pulumi.Aws.Ecr.Repository(...);

var ecrRegistry = Pulumi.Aws.Ecr.GetCredentials
    .Invoke(new Pulumi.Awss.Ecr.GetCredentialsInvokeArgs { RegistryId = repo.RegistryId })
    .Apply(creds =>
    {
        var decodedCredentials = Encoding.UTF8.GetString(Convert.FromBase64String(creds.AuthorizationToken)).Split(':');
        return new Pulumi.Docker.ImageRegistry
        {
            Server = creds.ProxyEndpoint,
            Username = decodedCredentials[0],
            Password = decodedCredentials[1],
        };
    });

var image = new Pulumi.Docker.Image("image", new Pulumi.Docker.ImageArgs
{
    ImageName = Output.Format($"{repo.RepositoryUrl}:my-tag")
    Registry = ecrRegistry,
    Build = ...
});
```

This works fine for a while, but AWS ECR tokens are only good for 12 hours. After that time, I start seeing "token expired" error messages.

### Expected Behavior

I expected that the results of my `Ecr.GetCredentials` data source would be used in the creation of the `Docker.Image`, and succesfully push.

### Actual Behavior

Docker image fails to push with expired token error message.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @dferretti - thank you so much for reporting.

We are working on a new major version of this provider that is projected to fix this.

**Comment by guineveresaenger** [comment]
This is fixed on [this prerelease version](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0-alpha.3).
