### ISSUE TITLE
Package now requires config

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-docker#49]
Unless I'm mistaken, the failure in https://travis-ci.com/pulumi/examples/jobs/162164624 is due to the addition of the Terraform provider to this module. It seems now to use the package, you are required to set the `docker:host` config variable (per https://github.com/pulumi/pulumi-docker/blob/dc615f276b40096146e21af5cd8c248f6ab16d5e/sdk/nodejs/config/vars.ts#L24). This doesn't seem to be what we want.

**Comment by CyrusNajmabadi** [comment]
Thanks!
