### ISSUE TITLE
Consider supporting additional input credentials for build and cache pull

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-docker#497]
As a followup to #495, we may want to consider passing in additional registry credentials to the provider to enable a scenario where we are pulling cache from a different registry than the one the `Image` resource is targeting.

**Comment by blampe** [comment]
No plans to implement this in this provider, but it is supported in the new Docker Build provider.

Repository [here](https://github.com/pulumi/pulumi-docker-build), announcement [here](https://www.pulumi.com/blog/docker-build/), API docs [here](https://www.pulumi.com/registry/packages/docker-build/).
