### ISSUE TITLE
Add repo digests as outputs

### ISSUE THREAD

**Issue by antifuchs** [pulumi/pulumi-docker#507]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I was just trying out the pulumi-docker 4.0 alphas, and it seems to work really well! However, In our IaC repo, we rely on the repository digests to firmly pin the docker image used for containers using them subsequently. In [pulumi-docker-buildkit](https://github.com/MaterializeInc/pulumi-docker-buildkit/blob/master/cmd/pulumi-resource-docker-buildkit/main.go#L310-L325) we use the first of the digests emitted by docker, but I think having all available or only the first one would be workable for us.

### Affected area/feature

Just the pulumi-docker provider.

**Comment by AaronFriel** [comment]
@antifuchs Thanks for flagging this need, is it an acceptable workaround to use a git commit or SHA in the tag of the `imageName`? 

In switching to the Docker Client SDK, we found that it does not expose the image manifest digest on build or push, and we want to avoid shelling out to `docker inspect` to discover the digest as issues around running the docker CLI contributed to many of the issues we resolved in v4.

**Comment by benesch** [comment]
So we'd really like to avoid mutable tags in our deployment pipeline. When developing locally, it's common to run `pulumi up` repeatedly on the same Git commit. There just isn't a good Docker tag to use to describe the repository state _besides_ the SHA of the Docker image itself.

> In switching to the Docker Client SDK, we found that it does not expose the image manifest digest on build or push, and we want to avoid shelling out to `docker inspect` to discover the digest as running the docker CLI contributed to many of the issues we resolved in v4.

This is very surprising! I imagine `docker inspect` is using some API that Pulumi could also use? I'll dig into this.

**Comment by benesch** [comment]
> > In switching to the Docker Client SDK, we found that it does not expose the image manifest digest on build or push, and we want to avoid shelling out to `docker inspect` to discover the digest as running the docker CLI contributed to many of the issues we resolved in v4.
> 
> This is very surprising! I imagine `docker inspect` is using some API that Pulumi could also use? I'll dig into this.

Here ya go: https://github.com/pulumi/pulumi-docker/pull/530

**Comment by andrekiba** [comment]
thanks, when this will be released?

**Comment by guineveresaenger** [comment]
We're waiting on #530, requested a few changes
