### ISSUE TITLE
Docker Build Issue

### ISSUE THREAD

**Issue by stephenbawks** [pulumi/pulumi-docker#528]
### What happened?

I started using the new pulumi-docker 4.0 and I have modified my docker image resource (using Python) and doing this in Windows.

Currently getting this issue:

error: failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 1: unknown instruction:

When I build from the CLI it works with no issues.

```
build_container = docker.Image(
    "build_container",
    image_name=my_ecr.repository_uri,
    build={
        "context": "./src/fakename",
        "platform": "linux/x86_64",
    },
    registry={
        "server": my_ecr.repository_uri.apply(lambda uri: uri.split("/")[0]),
        "username": ecr_token.user_name,
        "password": ecr_token.password,
    },
    opts=pulumi.ResourceOptions(parent=my_ecr)
)
```

I have tried a bunch of different options for `platform`  and have had no luck.  I have tried specifying the `build_version` and trying to specify Build Kit.  I have tried setting buildkit to false in my Docker settings and still have had no luck.  I am honestly not sure what I am missing at the moment.

### Expected Behavior

Docker Build the container

### Steps to reproduce

```
build_container = docker.Image(
    "build_container",
    image_name=my_ecr.repository_uri,
    build={
        "context": "./src/fakename",
        "platform": "linux/x86_64",
    },
    registry={
        "server": my_ecr.repository_uri.apply(lambda uri: uri.split("/")[0]),
        "username": ecr_token.user_name,
        "password": ecr_token.password,
    },
    opts=pulumi.ResourceOptions(parent=my_ecr)
)
```

### Output of `pulumi about`

```
Diagnostics:
  docker:index:Image (my-container):
    error: failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 1: unknown instruction:
```
  

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Hey @stephenbawks, thanks for filing this and providing a repro. We're going to look into this.

Is there anything that might be unusual about the Dockerfile, or is it the standard syntax beginning with `FROM ...`? Asking as there are some [exotic Dockerfile features](https://docs.docker.com/build/buildkit/dockerfile-frontend/) that could be significant for the repro.

**Comment by stephenbawks** [comment]
@AaronFriel I do not believe so.  

```
FROM public.ecr.aws/lambda/python:3.9

COPY requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt --target ${LAMBDA_TASK_ROOT}

COPY ./app ${LAMBDA_TASK_ROOT}

CMD ["lambda_function.lambda_handler"]
```

**Comment by AaronFriel** [comment]
Thanks for confirming, very helpful!

**Comment by AaronFriel** [comment]
@stephenbawks If you convert the Dockerfile to Linux line endings, using e.g. `dos2unix PATH_TO_DOCKERFILE`, does that resolve the build issue?

If that's the solution, we'll need to look into how the Docker CLI supports this.

**Comment by stephenbawks** [comment]
@AaronFriel 

Does not appear to make a difference.

**Comment by AaronFriel** [comment]
@stephenbawks Could you try setting platform to `"linux/amd64"`?

It looks like this error occurs in the Docker Engine when I set an invalid platform string.

**Comment by AaronFriel** [comment]
@stephenbawks It looks like this may be a few issues compounding on one another. We're working on a fix for this.

**Comment by stephenbawks** [comment]
> @stephenbawks Could you try setting platform to `"linux/amd64"`?
> 
> It looks like this error occurs in the Docker Engine when I set an invalid platform string.

When I try this locally I am getting:

```
docker:index:Image (rss-feed-container):
    error: Error response from daemon: invalid reference format: repository name must be lowercase
```

**Comment by stephenbawks** [comment]
@AaronFriel 

Just thought I would check back in to see if there were any updates.  Thanks!

**Comment by guineveresaenger** [comment]
Hi @stephenbawks - we have released a few patches since this issue was filed. Could you try with version 4.1.2 and let us know how it goes?

**Comment by guineveresaenger** [comment]
hey again @stephenbawks - would love to hear if this is still an issue. Thanks!

**Comment by guineveresaenger** [comment]
In the meantime, we have fixed some issues around specifying the platform. Please feel free to re-open!
