### ISSUE TITLE
Improve provider automatic TLS configuration

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-docker#531]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The Docker  daemon (`dockerd`) communicates over 2 well-known ports `2375` (plain text) and `2376` (encrypted) ([ref](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option)). This `pulumi-docker` provider, uses `DOCKER_HOST` as the default Docker host ([ref](https://www.pulumi.com/registry/packages/docker/installation-configuration/)). 

However, when port `2376` is used (ie, `tcp://localhost:2376`), this provider doesn't automatically switch to TLS communication resulting in the following error message (even during the `preview`, when the provider _pings_ the `dockerd` service.).

```
Error pinging Docker server: Error response from daemon: Client sent an HTTP request to an HTTPS server.
```

Rather than requiring developers to create a separate provider instance, it would be nice if this provider could look into `$HOME/.docker/` as a default location to find the client TLS materials so it mimics the same behavior as the `docker` client ([ref](https://docs.docker.com/engine/reference/commandline/docker/#options)).

### Affected area/feature

* provider

**Comment by guineveresaenger** [comment]
Hi @aureq - we did do some work on this in #570 and #574 that should allow the provider to just use TLS with the correct key config settings.

Is there any functionality still missing that you would like to see?

**Comment by aureq** [comment]
I think that should be good for now. I'll close this issue. Thank you for working in this.
