### ISSUE TITLE
Add support for `--secret` from `buildx`

### ISSUE THREAD

**Issue by NakulK48** [pulumi/pulumi-docker#539]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Now that the `extraOptions` field is gone, there is no way of mounting a secret into the docker build, which is the recommended way of making use of secret keys when building.

https://docs.docker.com/engine/reference/commandline/buildx_build/#secret

I imagine supporting the full `extraOptions` is infeasible because of the move away from the docker CLI, but it would be helpful to have this available as a top-level field.

**Comment by mike-chen-samsung** [comment]
Would like to add that doing something like this results in an error, so I don't think it's even possible to use v4 of this package to securely build images that require secrets. Or can someone point out a workaround?
```
build: {
  args: {
    NPM_TOKEN: secret(process.env.NPM_TOKEN!),
```

```
panic: interface conversion: interface {} is *resource.Secret, not resource.PropertyMap
```

**Comment by Jomik** [comment]
This seems like a pretty big caveat. 
Can we expect to get this fixed so that we can properly build images that depend on private/secret resources?

**Comment by ShedPlant** [comment]
I already migrated to pulumi-docker 4 and realised I now can't use `--secret` at build time 😞 .

**Comment by ShedPlant** [comment]
@mike-chen-samsung can you please explain your workaround and its limitations?

Is there any chance of this being worked on in 2024?

Currently:
- my docker images need AWS CodeArtifact credentials to download libraries
- the credentials are copied into the docker image for the purpose of downloading the libraries
- the credentials are temporary for the developer or the CI run
- therefore the next CI run uses different credentials
- the docker cache is invalidated
- builds are less secure and slower to build than I would like

**Comment by mike-chen-samsung** [comment]
@ShedPlant my workaround is the same as what you're doing - we must copy the creds into the docker image which invalidates cache

**Comment by ascrookes** [comment]
Just adding a +1 that my team would also benefit from this feature. It is blocking us from using `pulumi-docker`. We have a similar workflow as @ShedPlant of needing to install from CodeArtifact as part of a build step and mounting the secret is the most secure way to go about that.

**Comment by blampe** [comment]
Hi folks, we just released a new Docker Build provider focused exclusively on building images with buildx/BuildKit. It provides `--secret` functionality out of the box, and we recommend you use it for building images going forward. Please take a look and give us feedback!

The repository is [here](https://github.com/pulumi/pulumi-docker-build); our blog announcement is [here](https://www.pulumi.com/blog/docker-build/); and finally API docs are [here](https://www.pulumi.com/registry/packages/docker-build/) along with examples of how to migrate your existing `Image` resources to `dockerbuild.Image`.

We won't be able to add this functionality in this provider for a number of reasons, so I'm closing this as wont-fix.

**Comment by ShedPlant** [comment]
Very exciting, thanks @blampe !

**Comment by saadismail** [comment]
@ShedPlant but doesn't it still "rebuild" the images every time CodeArtifact token changes in the CI?

If not, if you could share a boilerplate of your setup, that would be amazing.
