### ISSUE TITLE
Option to re-enable docker build on preview

### ISSUE THREAD

**Issue by NakulK48** [pulumi/pulumi-docker#540]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I noted in the `v4.0.0` changelog that running `pulumi preview` on a stack containing a `docker.Image` will no longer build the image https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0

This is advertised as a feature, but we actually find it quite useful to have a verification of the correctness of a dockerfile before applying the update (e.g. to run in CI on every commit in a PR). Is it possible to have a flag that re-enables preview building, or is there a better approach to validating the dockerfile pre-release?

### Affected area/feature

Something like:

```typescript
const image = new docker.Image(deploymentName, {
  build: {
    context: "..",
    dockerfile: "../docker/Dockerfile",
  },
  imageName: repo.repositoryUrl,
  localImageName: deploymentName,
  buildOnPreview: true
});

```

**Comment by AaronFriel** [comment]
@NakulK48 Thanks for flagging this as a feature request! Could you add an example of how a user would use this flag to your issue?

**Comment by joewragg** [comment]
+1 for this

**Comment by AaronFriel** [comment]
What behavior would you expect if you passed this flag and any other property was unknown. This would occur if it was an Output that hadn't been resolved at preview time.

Do we:

1. Skip the build despite the flag, silently continue.

2. Fail with an error

3. Try the build with the option ignored

**Comment by pgavlin** [comment]
I’d say skip the build and issue a status log message to notify the user that the build was skipped.

**Comment by stakauskas** [comment]
Commenting here as well. Would be great to have it as a switch. Used it to separate build / deploy stages, as in: build images on preview and only reference images on deploy. This way ensuring no time is wasted during deploy on image builds and ensuring that there will be no build failures on deploy.
