### ISSUE TITLE
docker.Image does not read host value from provider-level config

### ISSUE THREAD

**Issue by bgroupe** [pulumi/pulumi-docker#567]
### What happened?

When building an image w/ `docker.Image` the host value is not read when set at the config level, as outlined in option 2 in the docs [here](https://www.pulumi.com/registry/packages/docker/installation-configuration/). It is also not read when the provider is explicitly configured with a host value. It is only respected by the env var `DOCKER_HOST`.

### Expected Behavior

The host value is read from the documented methods. 

### Steps to reproduce

**Context**: Distributions such as Docker Desktop start the daemon on a socket in a local directory and thus the default `unix:///var/run/docker.sock` ends up being something like `unix:///Users/<user>/.docker/run/docker.sock`.  in the provider docs there are two options listed for specifying the host, the second being to set the `docker:host` provider key. However this does not get picked up when you are building an image with the following: 

```python 
 dev_build = docker.Image(
        "airflow-dev",
        build={
            "context": "../",
            "dockerfile": "../Dockerfile",
        },
        image_name="local/myimage:dev",
        skip_push=True,
    )
```

and results in 

```
error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

If you explicitly configure a provider like this:

```python
provider = docker.Provider(
    "docker-provider",
    host="unix:///Users/<my-user>/.docker/run/docker.sock",
    registry_auth=[provider_registry_auth],
)

dev_build = docker.Image(
        "airflow-dev",
        build={
            "context": "../",
            "dockerfile": "../Dockerfile",
        },
        image_name="local/myimage:dev",
        skip_push=True,
        opts=pulumi.ResourceOptions(provider=provider)
    )
```

The result is the same. Only when exporting `DOCKER_HOST` in your shell does it work as intended. 

### Output of `pulumi about`

```
CLI          
Version      3.59.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.0.1
gcp     6.51.0
python  unknown

Host     
OS       darwin
Version  12.1
Arch     arm64

This project is written in python: executable='/Users/bgroupe/.asdf/shims/python3' version='3.10.10
'

Current Stack: dev1

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:dev1::airflow-local::pulumi:pulumi:Stack::airflow-local-dev1
pulumi:providers:docker               urn:pulumi:dev1::airflow-local::pulumi:providers:docker::docker-provider
docker:index/network:Network          urn:pulumi:dev1::airflow-local::docker:index/network:Network::airflow-network
docker:index/remoteImage:RemoteImage  urn:pulumi:dev1::airflow-local::docker:index/remoteImage:RemoteImage::airflow-postgres
docker:index/remoteImage:RemoteImage  urn:pulumi:dev1::airflow-local::docker:index/remoteImage:RemoteImage::airflow-redis
docker:index/container:Container      urn:pulumi:dev1::airflow-local::docker:index/container:Container::airflow-postgres
docker:index/container:Container      urn:pulumi:dev1::airflow-local::docker:index/container:Container::airflow-redis
docker:index/image:Image              urn:pulumi:dev1::airflow-local::docker:index/image:Image::airflow-dev


Found no pending operations associated with dev1

Backend        
Name           bgroupe.local
URL            file://~
User           bgroupe
Organizations  

Dependencies:
NAME           VERSION
pip            23.0.1
pulumi-docker  4.0.1
pulumi-gcp     6.51.0
setuptools     67.6.0
wheel          0.40.0
```

### Additional context

The issue with the provider could also be related to this issue I filed #550 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @bgroupe - thank you for filing this issue - this is a config oversight and we'll be working on a fix soon.

**Comment by bgroupe** [comment]
@guineveresaenger I see that this was mentioned in release 4.1.1 but I am still able to reproduce this.

**Comment by guineveresaenger** [comment]
@bgroupe how are you setting the docker host in your config? what does your Pulumi.stack.yaml look like?

**Comment by bgroupe** [comment]
I'm setting `docker:host` like

```yaml 
encryptionsalt: foo
config:
  ...
  docker:host: unix:///Users/bgroupe/.docker/run/docker.sock
  ...
```

**Comment by guineveresaenger** [comment]
@bgroupe thank you for that info! your config looks correct. It does look like this error is now on a different resource though - can you help me understand whether this is still happening on `docker.Image`? I ask because `Network` accesses the config differently from `Image`.
