### ISSUE TITLE
docker:index:Image could not open dockerfile at relative path Dockerfile

### ISSUE THREAD

**Issue by ShedPlant** [pulumi/pulumi-docker#572]
### What happened?

Upgraded from `pulumi-docker` `4.0.0` to `4.1.0`.
`pulumi up` unexpectedly errors:

```
Diagnostics:
  docker:index:Image (my-app:latest):
    error: could not open dockerfile at relative path Dockerfile. Try setting `dockerfile` to "/Users/shed/Repos/my-repo/projects/my-app/Dockerfile"
```

### Expected Behavior

`pulumi up` to locate `Dockerfile` relative to my project directory.

### Steps to reproduce

My pulumi resource looks something like:

```python
image = docker.Image(
            "my_app:latest",
            build=docker.DockerBuildArgs(
                context="/Users/shed/Repos/my-repo/projects/my-app/",
                dockerfile="Dockerfile",
                args={"BUILDKIT_INLINE_CACHE": "1"},  # may not be necessary?
                cache_from=docker.CacheFromArgs(
                    images=[
                        pulumi.Output.concat(repo.repository_url, ":", "latest")
                    ]
                ),
                platform="linux/amd64",
            ),
            registry=registry,
            image_name=pulumi.Output.concat(self.repo.repository_url, ":", "latest"),
        )
```

There is a file `/Users/shed/Repos/my-repo/projects/my-app/Dockerfile`.
`context` is set to the directory and `dockerfile` is explicitly set to `Dockerfile`.

### Output of `pulumi about`

I don't want to copy/paste this from a work project. I'll try to provide specific info as requested if relevant.

### Additional context

Split from #566

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ShedPlant** [comment]
As a workaround, if I set `dockerfile` to `None`, then the default behaviour of finding `Dockerfile` under the context seems to work as expected.

**Comment by guineveresaenger** [comment]
Hi @ShedPlant - thank you for filing this issue and apologies for the confusion!

This was a [breaking change for 4.0.1.](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.1)
We now expect the Dockerfile location to be relative to your Pulumi context, so we can allow for context-external Dockerfiles to be read in in a way the provider can detect. This actually mirrors the behavior of the Docker command line, so we decided it was an acceptable change.

Please reach out if you have further questions.

**Comment by sinclairnick** [comment]
FYI @guineveresaenger I've been experiencing a similar issue (`@pulumi/docker@4.1.2`). When the `cacheFrom` property was set, it seems, the Docker Image could "not be found":

```
// With config:
// `context`=../../
// `dockerfile`=../../apps/X/Dockerfile
error: could not open dockerfile at relative path Dockerfile. stat Dockerfile
```

I've since removed the `cacheFrom` field, to get around the issue, but thought I'd let y'all know.

**Comment by cnunciato** [comment]
@guineveresaenger I get the same behavior as @sinclairnick -- relative path doesn't work unless `cacheFrom` is removed. Should I file a separate issue or reopen this one?
