### ISSUE TITLE
in docker.Image, image fails to build when called twice

### ISSUE THREAD

**Issue by kamatsuoka** [pulumi/pulumi-docker#578]
### What happened?

Following https://pulumi-community.slack.com/archives/CJ909TL6P/p1678919350593459?thread_ts=1678915866.706349&cid=CJ909TL6P, I'm calling `docker.Image` twice in order to tag an image with a hash and with `latest`.  On Mac OS, this code works fine. but on Windows, it fails the second time with the error 
```
  docker:index:Image (test-image):
    error: error hashing dockerfile "test-image/Dockerfile": could not open file test-image/Dockerfile: open test-image\test-image\Dockerfile: The system cannot find the path specified.
```
here's the code in question:
```
  const buildImage = (
    name: string,
    imageDir: string,
    tag: string,
  ): docker.Image => {
    return new docker.Image(
      name,
      {
        build: {
          context: imageDir,
        },
        imageName: `${name}:${tag}`
      }
    )
  }
  const hash = "1234567890" 
  buildImage("test-image", "./test-image", "latest")
  buildImage("test-image-hash", "./test-image", hash)
```

### Expected Behavior

This code should work on Windows as well.

### Steps to reproduce

See the repo https://github.com/kamatsuoka/pulumi-docker-test. On Windows, run
```
yarn install
pulumi up
```

### Output of `pulumi about`

```
CLI
Version      3.60.1
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME     VERSION
aws      5.34.0
awsx     1.0.2
command  0.7.1
docker   4.1.1
docker   3.6.1
nodejs   unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in nodejs: executable='C:\Users\[xxxxxxx]\scoop\apps\nodejs\current\node.exe' version='v16.13.0'

Current Stack: monolith-corp/pulumi-docker-test/dev

TYPE                                     URN
pulumi:pulumi:Stack                      urn:pulumi:dev::pulumi-docker-test::pulumi:pulumi:Stack::pulumi-docker-test-dev
docker:image:Image                       urn:pulumi:dev::pulumi-docker-test::docker:image:Image::test-image
pulumi:providers:awsx                    urn:pulumi:dev::pulumi-docker-test::pulumi:providers:awsx::default_1_0_2
pulumi:providers:command                 urn:pulumi:dev::pulumi-docker-test::pulumi:providers:command::default_0_7_1
awsx:ecr:Repository                      urn:pulumi:dev::pulumi-docker-test::awsx:ecr:Repository::test-image-repo
command:local:Command                    urn:pulumi:dev::pulumi-docker-test::command:local:Command::test-image-get-ecr-password
pulumi:providers:aws                     urn:pulumi:dev::pulumi-docker-test::pulumi:providers:aws::default_5_16_2
aws:ecr/repository:Repository            urn:pulumi:dev::pulumi-docker-test::awsx:ecr:Repository$aws:ecr/repository:Repository::test-image-repo
aws:ecr/lifecyclePolicy:LifecyclePolicy  urn:pulumi:dev::pulumi-docker-test::awsx:ecr:Repository$aws:ecr/lifecyclePolicy:LifecyclePolicy::test-image-repo
pulumi:providers:pulumi                  urn:pulumi:dev::pulumi-docker-test::pulumi:providers:pulumi::default


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/kamatsuoka
User           kamatsuoka
Organizations  kamatsuoka, [xxxxxxxxxx]
```

### Additional context

This is a regression in @pulumi/docker 4.x. Works fine on Windows on @pulumi/docker 3.6.1.

Workaround: call `docker.Image` with the absolute path for the `context` directory.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Hey @kamatsuoka thank you for reporting this and giving us a repro. We'll take a look!

Out of curiosity, does the image succeed if you specify either the "latest" or hash on Windows, and fails if you specify both, with order not mattering?

**Comment by AaronFriel** [comment]
@kamatsuoka I was able to reproduce this issue regardless of the # of Image resources created.

As a workaround on Windows, you could set the context dir to "test-image" (no slash), or use local file path utilities in the programming language to generate a path that uses the OS's default separator. In TypeScript, I think that would be `join([...paths])` from the `path` module.

We're going to keep this issue open and I'm working on a fix with @guineveresaenger, we'll let you know when we have a fix.
