### ISSUE TITLE
Add support for SSH-based connection to Docker daemon

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-docker#580]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The `docker` CLI supports SSH-based connections, which greatly simplifies the use of remote systems for performing Docker operations, such as building images (very useful, for example, for building AMD64 images from an ARM64-based local system). However, the Docker provider does not seem to support SSH-based connections; it returns an error when attempting to use a `DOCKER_HOST` environment variable set to an SSH-based connection.

### Affected area/feature

Docker provider

**Comment by AaronFriel** [comment]
Thanks @scottslowe! 

For the use case in your issue, does setting `platform: "linux/amd64"` suffice to not require an SSH host? I understand there are other situations in which you want to connect to a further-remote host as well, if you have an example of that use case we can add it to the issue.

**Comment by scottslowe** [comment]
> does setting `platform: "linux/amd64"` suffice

Last time I tried it, the build ran for hours with no visible progress. I'm happy to try again.

In this particular instance, I have Pulumi code that builds container images and runs them, and this Pulumi code works flawlessly on an ARM64-based system. However, the exact same code does _not_ work correctly on an AMD64-based system, so I'm trying to determine why this is the case---hence trying to connect to a remote AMD64-based system.

**Comment by AaronFriel** [comment]
I wouldn't expect hours, but it should take longer: Docker is emulating amd64 and that can have performance costs. We'll definitely keep this as a feature request though.

**Comment by benesch** [comment]
We've got the same need at Materialize. Emulation of `linux/amd64` is also too slow us—it takes hours for our build too. (It actually takes so many hours that I've never bothered to wait around.)

Emulation works well when your Docker build is mostly installing packages and copying files into the image (e.g. for interpreted languages like Python). It's pretty much a no-go if you need to compile code during the build. In our case, we need to compile some significant Rust packages, and running `rustc` under emulation is intractable.

**Comment by guineveresaenger** [comment]
Hi @scottslowe and @benesch - docker v4.2.2 should include a [fix](#637) and I hope you can try it out!

**Comment by scottslowe** [comment]
Doesn't work for me, unfortunately. I set `DOCKER_HOST` to `ssh://user@ip-address` and get this when I run `pulumi up`:
```
    error: 1 error occurred:
    	* Error pinging Docker server: Error response from daemon: 400 Bad Request: malformed Host header
```
Running `docker` commands manually (like `docker container ls`) work as expected.

**Comment by necaris** [comment]
@guineveresaenger unfortunately this doesn't seem to play well with SSH configs or specifying the user in the URL, so I'm having trouble testing it locally, but will let you know once CI finishes if we have any luck:
```
 error: error during connect: Post "http://ubuntu%40developer-dockerbuilder.dev.materialize.com/v1.24/build?buildargs=%7B%22CARGO_RELEASE%22%3A%22%22%7D&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile.init&labels=null&memory=0&memswap=0&networkmode=&platform=linux%2Famd64&rm=0&session=q9xmkbsfa4rjsmpfihf9rqlda&shmsize=0&t=670453656796.dkr.ecr.us-east-1.amazonaws.com%2Fglobals-docker-images-mzcloud-init-container-026e793&target=init-container&ulimits=null&version=2": dial tcp: lookup ubuntu@instance-on-ec2: no such host
 ```

**Comment by necaris** [comment]
...well, CI passes `preview`, at least
