### ISSUE TITLE
Reports "Cannot connect to the Docker daemon at unix:///var/run/docker.sock" when use Colima as docker server

### ISSUE THREAD

**Issue by suerta-git** [pulumi/pulumi-docker#603]
### What happened?

When use Colima as docker server, the socket location is NOT `/var/run/docker.sock` by default: https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#docker-socket-location

Colima uses Docker contexts to make docker client connects to correct location.

### Expected Behavior

Identify the correct socket location by docker context, to be compatible with colima.

### Steps to reproduce

- Use Colima as docker server
- `pulumi up`

### Output of `pulumi about`

CLI          
Version      3.63.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME     VERSION
command  0.7.2
docker   4.1.2
docker   3.6.1
gcp      6.54.0
gcp      6.54.0
nodejs   unknown
random   4.12.1

Host     
OS       darwin
Version  12.6.2
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by suerta-git** [comment]
**Workaround: **
Set environment variable like option 2 https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running

**Comment by suerta-git** [comment]
And I feel that the building becomes significantly slower after I migrated @pulumi/docker from 3.x to 4.x caused by some reason :(.
Seams the layer caches are not hit correctly.

**Comment by guineveresaenger** [comment]
Hi @suerta-git - the way to set this for the Pulumi provider would be to [set your docker host in the provider config](https://www.pulumi.com/registry/packages/docker/installation-configuration/#configuring-the-provider). Env vars will work as well, as you discovered already.

As for the build speed, there is currently an upstream docker client bug that fails to cache on every second build.
We are [almost done with a fix for this in the provider](https://github.com/pulumi/pulumi-docker/pull/601) that will make it into the next minor release.

**Comment by guineveresaenger** [comment]
Docker v4.2.0 is currently being released. We hope this addresses your caching concerns - feel free to re-open if necessary.

I'm closing this as addressed in #601 for now. 🙇‍♀️

**Comment by suerta-git** [comment]
> Docker v4.2.0 is currently being released. We hope this addresses your caching concerns - feel free to re-open if necessary.

Thanks @guineveresaenger, I will have a try later.

> The way to set this for the Pulumi provider would be to [set your docker host in the provider config](https://www.pulumi.com/registry/packages/docker/installation-configuration/#configuring-the-provider). Env vars will work as well, as you discovered already.

I suggest you guys can add this use case into troubleshooting or somewhere because the error message is confusing for a person who is not very familiar with docker context.
