### ISSUE TITLE
"failed to read dockerfile" in 4.2.0 on Windows (works in 3.x)

### ISSUE THREAD

**Issue by alecor191** [pulumi/pulumi-docker#624]
### What happened?

I'm using Pulumi with C# on **Windows**. Since I upgraded `Pulumi.Docker` to `4.2.0` (from `3.6.1`) I get the following error when building a Dockerfile:

```bash
error: failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1961648446/EchoApp\Dockerfile: no such file or directory
```

Note the **backslash** before `Dockerfile`: `...EchoApp\Dockerfile`. I believe this is the culprit.

Here my C# code that produces the above:

```csharp
var imageArgs = new ImageArgs
{
    Build = new DockerBuildArgs
    {
        Context = "../../../Apps",
        Dockerfile = $"../../../Apps/{appSourcePath}/Dockerfile",
    },
    ...
};

new Image(appName, imageArgs);
```

Note how I only have forward `/` in the `Dockerfile` path.

### Expected Behavior

Dockerfile is built without errors.

### Steps to reproduce

Create an `Image` with some relative paths for `Context` and `Dockerfile`.

### Output of `pulumi about`

'dotnet build -nologo .' completed successfully
CLI
Version      3.66.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.102.0
docker        4.2.0
dotnet        unknown
kubernetes    3.26.0

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.203'

### Additional context

- I also tried to run the plain Docker CLI command and that works perfectly fine with parameters above:

  ```bash
  docker build -t echo-app -f ../../../Apps/EchoApp/Dockerfile ../../../Apps
  ```

- The above worked fine in `3.6.1` (just that the type was called `DockerBuild` and not `DockerBuildArgs` as in `4.x`).

Am I missing something?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by alecor191** [comment]
Thanks a lot @guineveresaenger for looking into this. I reviewed the path as suggested, but I believe it is correct:

I run `pulumi up` from the same path as the `Pulumi.yaml` file is located: `<base>/Stacks/Apps/ApiStack/Pulumi.yaml`.

And then configure context and Dockerfile relative paths as follows (the app with the Dockerfile is located in `<base>/Apps/EchoApp/`):

- Context: `../../../Apps`
- Dockerfile: `../../../Apps/EchoApp/Dockerfile`

So both paths are relative to the directory where `Pulumi.yaml` is located resp. the current directory where I run the `pulumi up` command.

**Comment by alecor191** [comment]
What's maybe also worth mentioning: If I provide a non-existing relative path for the Dockerfile, then the error message is a different one. 

Here an example:

Dockerfile path provided: `../../../does/not/exist/Dockerfile`

Error message shown by Pulumi CLI:

```bash
error: could not open dockerfile at relative path ../../../does/not/exist//Dockerfile: CreateFile ../../../does/not/exist//Dockerfile: The system cannot find the path specified.
```

So that also seems to indicate that the relative Dockerfile path mentioned above should be correct.

**Comment by guineveresaenger** [comment]
> error: could not open dockerfile at relative path ../../../does/not/exist//Dockerfile: CreateFile ../../../does/not/exist//Dockerfile: The system cannot find the path specified.

That error comes from the provider's filepath validation before we pass things along to the Docker client. The original error comes from the Docker client itself.

My best guess here is that Docker for Windows is substituting the backslash, which would normally provide no problem, but adding the relative filepath then combines the two conventions in a way that Docker cannot open.

I'm unfortunately not able to repro this on my non-Windows machine, but I will get a colleague looking into this as soon as we can. 

Another idea in the meantime would be to try using all back slashes in your Dockerfile path, as Docker should respect backslashes.

**Comment by alecor191** [comment]
Thanks @guineveresaenger. I tried to use only backslash, but it leads to the same result. Further, even if it worked, I don't think replacing `/` with `\` would be an option: while I develop on Windows, the same Pulumi project is also executed as part of CI pipelines that run on Linux.

> My best guess here is that Docker for Windows is substituting the backslash,

Please note that building the project using Docker CLI works fine:

```bash
docker build -t echo-app -f ../../../Apps/EchoApp/Dockerfile ../../../Apps
```

**Comment by alecor191** [comment]
@guineveresaenger do you have an update on this topic? Were you able to repro on Windows resp. is there any additional information I can provide?

**Comment by guineveresaenger** [comment]
Hi @alecor191 - repro was a matter of finding a windows machine - but we have a fix for this up awaiting review.

**Comment by alecor191** [comment]
Thanks a lot @guineveresaenger for addressing this so quickly! Do you know in what release this change will be included and what the timeframe is?

**Comment by guineveresaenger** [comment]
I'm cutting the 4.2.3 patch now and it should be available to you shortly!
