### ISSUE TITLE
Can't connect to remote Docker via SSH

### ISSUE THREAD

**Issue by octet-stream** [pulumi/pulumi-docker#662]
### What happened?

Hi. First of all, thanks for making Pulumi! I think it's pretty amazing tool.

I'm trying to deploy one of my applications to DigitalOcean server using Pulumi + Docker via SSH connection. While from Docker CLI this seem to work and pretty simple to set up, pulumi fails to build an image on remote server. From the look of the error I'm getting, it seems like after ssh connection is established, pulumi (or docker?) completely ignoring the fact I'm working via SSH, and proceeds building image via http for some reason. You can find more information by the link below. This happens at least when I'm using pulumi YAML runtime.

### Expected Behavior

Docker connection to remote server is succeeded (which is seem to work), my image is sent and built on that server, and container is up and running (which doesn't work).

### Steps to reproduce

You can find all steps in this repository: https://github.com/octet-stream/pulumi-docker-ssh-issue

It also includes a simple example TCP server and a Dockerfile to build an image for that server.

### Output of `pulumi about`

CLI          
Version      3.72.2
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
docker  unknown
yaml    unknown

Host     
OS       darwin
Version  13.4
Arch     arm64

This project is written in yaml

Current Stack: octet-stream/pulumi-docker-ssh-issue/dev

TYPE                     URN
pulumi:pulumi:Stack      urn:pulumi:dev::pulumi-docker-ssh-issue::pulumi:pulumi:Stack::pulumi-docker-ssh-issue-dev
pulumi:providers:docker  urn:pulumi:dev::pulumi-docker-ssh-issue::pulumi:providers:docker::default
pulumi:providers:docker  urn:pulumi:dev::pulumi-docker-ssh-issue::pulumi:providers:docker::docker-remote

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/octet-stream
User           octet-stream
Organizations  octet-stream

No dependencies found

### Additional context

Along with the `pulumi about` information: I'm using docker `v24.0.2` on the client and `19.03.14` on the server.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by octet-stream** [comment]
Figured out this is only happen with `docker:Image` resources. The error message suggests it too - from what I can tell, docker sends the image over `http` for some reason.

I've updated the repository with `mysql-test-image` and `mysql-test-container` resources. Both of which deployed successfully, unlike `my-image`.

**Comment by octet-stream** [comment]
I am not familiar with Go, pulumi's codebase or terraform, but I did a little investigation myself anyway, just out of curiosity. An I've come to the conclusion that pulumi seem to re-use `Container` resource from terraform, while for `Image` you have your own implementation. This implementation also has separate client instance for Docker APIs here: https://github.com/pulumi/pulumi-docker/blob/0e49fdeece93f6ed11fd627ec7b1b16ac3476e10/provider/image.go#L777-L785

And I think this client ignores ssh connections.

While terraform creates client here, in config https://github.com/kreuzwerker/terraform-provider-docker/blob/54685a5fb9b375961620d2c555c7f3925327112c/internal/provider/config.go#L121-L132 and then I think it's just reused (here for example: https://github.com/kreuzwerker/terraform-provider-docker/blob/54685a5fb9b375961620d2c555c7f3925327112c/internal/provider/resource_docker_container_funcs.go#L51). This I think is the reason why Container and RemoteImage resources being created on remote machine via SSH connection without any problem.

But these are just my assumptions, ofc.

**Comment by guineveresaenger** [comment]
Hi @octet-stream - thank you so much for the excellent repro and the digging here! You're right that we have to re-implement some of the client logic, and didn't ensure to add SSH connectivity as well.

I pushed a fix that should address this! 🤞
