### ISSUE TITLE
Image: can we add --pull and --no-cache options?

### ISSUE THREAD

**Issue by jdahlq** [pulumi/pulumi-docker#666]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

[`docker.Image`](https://www.pulumi.com/registry/packages/docker/api-docs/image/) doesn't have the ability to force a re-pull of the base image. For example, if I have a Dockerfile like this...

```dockerfile
FROM cloudflare/cloudflared:latest
CMD ["version]
```

... then Docker won't pull the newest version of the `cloudflare/cloudflared` base image if there is one cached locally.

Could we expose the `--pull` and `--no-cache` flags as `Image` arguments? Looks fairly straightforward to plumb them through to the underlying Docker Client: [PullParent](https://github.com/moby/moby/blob/b3843992fc12536908fea2fea3ece05725b1e613/api/types/client.go#L165) and [NoCache](https://github.com/moby/moby/blob/b3843992fc12536908fea2fea3ece05725b1e613/api/types/client.go#L162).

I realize that I could (should?) explicitly version the base image in the Dockerfile. But for some things, I just want to deploy the latest stable version once a week, for example.

### Affected area/feature

Pulumi Docker Provider

**Comment by t0yv0** [comment]
Thanks for filing this @jdahlq ! This indeed sounds like a great improvement. 

Anyone interested in this issue: upvoting helps my team prioritize; we're also open for contributions and can help shepherd a PR if anyone is interested. 

Docker.Image is currently hand-crafted and not mapped to the upstream provider but it is possible to enhance its functionality.

CC @guineveresaenger in case you are aware of any duplicate requests for this.

**Comment by jdahlq** [comment]
I can take a crack at it if you'd like. Since it is hand-crafted, I assume I'd need to manually plumb it through to all the SDKs? Looking through the recent commits, [this one that adds `platform` support](https://github.com/pulumi/pulumi-docker/commit/8ef5144443dcfdd4f90cc13ff25576fe933ce13b) looks like a good example for me to use?

**Comment by t0yv0** [comment]
Yes that looks like a good example, thank you! You don't need to do anything special for SDKs as they will be re-generated from the schema.

**Comment by blampe** [comment]
Hi @jdahlq, we just released a new Docker Build provider focused exclusively on building images with buildx/BuildKit. It provides `--pull` and `--no-cache` functionality out of the box, and we recommend you use it for building images going forward. Please take a look and give us feedback!

The repository is [here](https://github.com/pulumi/pulumi-docker-build); our blog announcement is [here](https://www.pulumi.com/blog/docker-build/); and finally API docs are [here](https://www.pulumi.com/registry/packages/docker-build/) along with examples of how to migrate your existing `Image` resources to `dockerbuild.Image`.

We won't be able to add this functionality in this provider for a number of reasons, so I'm closing this as wont-fix.
