### ISSUE TITLE
Version 4.x: unable to hash build context ... could not open file, permission denied

### ISSUE THREAD

**Issue by elderapo** [pulumi/pulumi-docker#675]
### What happened?

```bash
Diagnostics:
  docker:index:Image (microservice-*****):
    error: unable to hash build context: error while hashing "db/ca-key.pem": could not open file /home/user/project/db/ca-key.pem: open /home/user/project/db/ca-key.pem: permission denied
```

### Expected Behavior

It should omit `/home/user/project/db/` because of:
```.gitignore
...

# MySQL database directory
db/

...
```
entry in `.gitignore` (`/home/user/project/.gitignore`).

### Steps to reproduce

`/home/user/project/db/` is a volume from `percona:8.0.29-21` container.

### Output of `pulumi about`

CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v19.9.0'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@elderapo sorry you ran into this! I hope I'm able to help.

Can you provide the `@pulumi/docker` version you're using? I think we've changed the hashing code in a recent release, and the error message you're seeing doesn't line up with the current implementation.

If you could try updating to the latest release - v4.3.0 - let us know if that works. If not, can you provide us with any more details or an example program to reproduce? It looks like we'd need a file with different user permissions inside the build context, but a Git repo with a worked example is amlways best.

**Comment by elderapo** [comment]
@AaronFriel There you go https://github.com/elderapo/pulumi-docker-bug.

For some reason `.dockerignore` doesn't get respected when there is a custom docker file: `docker/Dockerfile.api`. If you rename it to `docker/Dockerfile` on disk and [update it there](https://github.com/elderapo/pulumi-docker-bug/blob/master/packages/deployer/src/stack.ts#L11) it works :thinking:.

**Comment by AaronFriel** [comment]
I think we follow the same rules as `docker build`, when specifying a Dockerfile name other than "Dockerfile", the name should be `$(Dockerfilename).dockerignore`, in your case: `Dockerfile.api.dockerignore`.

**Comment by elderapo** [comment]
Well if you build an image in that preproduction repo using docker it works just fine.

**Comment by AaronFriel** [comment]
@elderapo I see - it looks like on Docker we need to fallback to reading `.dockerignore` when the other file doesn't exist.

> Also `.dockerignore` is in the project root directory (just like `.gitignore`), it doesn't make sense for it to be inside of `docker/` since the build context is the root directory.

No disagreement there, we don't look inside `docker/` in that case.

**Comment by mike-chen-samsung** [comment]
> I think we follow the same rules as docker build, when specifying a Dockerfile name other than "Dockerfile", the name should be $(Dockerfilename).dockerignore, in your case: Dockerfile.api.dockerignore.

I have not found this to be true. `@pulumi/docker` version `4.4.2` seems to ignore all dockerignore files except the `.dockerignore` at the root. I've tried these without success:

```
custom.Dockerfile
custom.Dockerfile.dockerignore
Dockerfile.custom
Dockerfile.custom.dockerignore
```

**Comment by blampe** [comment]
https://docs.docker.com/build/building/context/#dockerignore-files

> When you run a build command, the build client looks for a file named .dockerignore in the root directory of the context. If this file exists, the files and directories that match patterns in the files are removed from the build context before it's sent to the builder.
> ...
> A Dockerfile-specific ignore-file takes precedence over the .dockerignore file at the root of the build context if both exist.

Relevant bits where we're checking one location but not both:

https://github.com/pulumi/pulumi-docker/blob/777e16ee4d6a21e0feb920e99155e0db0c99a9a0/provider/image.go#L120-L123

https://github.com/pulumi/pulumi-docker/blob/777e16ee4d6a21e0feb920e99155e0db0c99a9a0/provider/provider.go#L544-L545

@mike-chen-samsung was your build context `/` (and not `/docker/`)? If so I think you want something like this:
```
docker/
  custom.Dockerfile
custom.Dockerfile.dockerignore
```

**Comment by mike-chen-samsung** [comment]
@blampe Yup, my build context was `/`. The Docker documentation states:

> If you use multiple Dockerfiles, you can use different ignore-files for each Dockerfile. You do so using a special naming convention for the ignore-files. **Place your ignore-file in the same directory as the Dockerfile**

I hjust your suggestion of putting `custom.Dockerfile.dockerignore` at the root and it works! But Docker's documentation is pretty explicit about putting it in the same directory as `custom.Dockerfile`, not necessarily at the root of the context.

**Comment by blampe** [comment]
> I hjust your suggestion of putting `custom.Dockerfile.dockerignore` at the root and it works! But Docker's documentation is pretty explicit about putting it in the same directory as `custom.Dockerfile`, not necessarily at the root of the context.

For sure, and that's the bug I'll be looking into. Just wanted to point out we're currently always checking the root of the context, so that's available as a workaround until the bug is fixed.
