### ISSUE TITLE
`pulumi up` with YAML runtime fails on any change in build context, `Dockerfile`, or `Pulumi.yaml` config

### ISSUE THREAD

**Issue by octet-stream** [pulumi/pulumi-docker#685]
### What happened?

When updating resources with `pulumi up` command it fails when any change for `Image` resource occurs. This seem to happen with YAML runtime only, because I have another project with `Image` resources and Node.js runtime and everything works as expected. See `Steps to reproduce` section for more information. The error thrown by `pulumi up` command complains about missing `container.image` property, but as you can see in `Pulumi.yaml` config, this property is set.

Also, it would be nice if documentation has examples for `Image` resource usage with `Container`.

### Expected Behavior

When something is changed within build context, `Dockerfile` or `Pulumi.yaml` config the `pulumi up` command succeeds with no error.

### Steps to reproduce

I have created an example repository where you can see this issue in action: https://github.com/octet-stream/pulumi-yaml-image-update-issue

1. Clone this repository.
2. Log in to your pulumi account from command line.
3. Run `pulumi up -y` in project's root for the first time. It will set up resources. This command will succeed.
  3.1. Optionally, you can open [`http://localhost:3000`](http://localhost:3000) in your browser to verify that the app is up and running (you'll see the default Astro page)
4. Change something within build context, `Dockerfile`, or `Pulumi.yaml` config (you may just uncomment [line 32](https://github.com/octet-stream/pulumi-yaml-image-update-issue/blob/fdb795e6dd17f67598b6ddbf3d5c342cb1df7924/Dockerfile#L32))
5. Run `pulumi up -y` again and you'll see an error.

### Output of `pulumi about`

CLI          
Version      3.75.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
docker  unknown
yaml    unknown

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in yaml

Current Stack: octet-stream/pulumi-yaml-image-update-issue/dev

TYPE                              URN
pulumi:pulumi:Stack               urn:pulumi:dev::pulumi-yaml-image-update-issue::pulumi:pulumi:Stack::pulumi-yaml-image-update-issue-dev
pulumi:providers:docker           urn:pulumi:dev::pulumi-yaml-image-update-issue::pulumi:providers:docker::default
docker:index/image:Image          urn:pulumi:dev::pulumi-yaml-image-update-issue::docker:index/image:Image::image
docker:index/container:Container  urn:pulumi:dev::pulumi-yaml-image-update-issue::docker:index/container:Container::container

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/octet-stream
User           octet-stream
Organizations  octet-stream

No dependencies found

### Additional context

Docker version: 24.0.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
@octet-stream Thanks for reporting this issue. I'm able to reproduce this locally and can confirm it only affects yaml and not the nodejs provider. @guineveresaenger Would you have any idea what's happening here?

**Comment by guineveresaenger** [comment]
Hi @octet-stream - I found a workaround that may help you.

Rather than using  `baseImageName` in [this line](https://github.com/octet-stream/pulumi-yaml-image-update-issue/blob/main/Pulumi.yaml#L19), use `imageName`. The two are functionally the same; we kept `baseImageName` around for backwards compatibility.

Please let us know if that helps you out!

This may be an instance of output properties not getting populated correctly on update when using yaml, so we will keep this ticket open for further investigation.

**Comment by octet-stream** [comment]
Yes, this seem to work, many thanks!

Also, I missed the fact that

> The fully qualified image name that was pushed to the registry.

This is what happen when you read the documentation between the lines, so I had no idea I could've just use that property.
But the documentation have no examples with `Image` and `Container`, so I was a bit confused.

> ...we kept baseImageName around for backwards compatibility.

So it deprecated then?

**Comment by guineveresaenger** [comment]
It will be soon! :) glad you're unblocked for now!

**Comment by guineveresaenger** [comment]
I'm closing this issue in favor of https://github.com/pulumi/pulumi-yaml/issues/466.

In case we come back to determine that this is an issue with this provider, we will re-open.
