### ISSUE TITLE
Resource type `Provider` does not seem to respect `sshOpts` anymore

### ISSUE THREAD

**Issue by paschi** [pulumi/pulumi-docker#702]
### What happened?

I'm trying to connect to Docker on a remote host by using SSH. When using the `sshOpts` property of the `Provider` resource type to pass a user name and SSH private key file, the arguments are not passed to the SSH command line it seems.

### Expected Behavior

The `sshOpts` should be passed as arguments when using SSH.

### Steps to reproduce

I'm using the following config:
```typescript
const provider = new docker.Provider("docker-provider", {
    host: pulumi.interpolate`ssh://${server.ipv4Address}`,
    sshOpts: [
        "-l", "docker",
        "-i", "private-key",
        "-o", "StrictHostKeyChecking=no",
        "-o", "UserKnownHostsFile=/dev/null"
    ],
});

const remoteImage = new docker.RemoteImage("image", {
    name: "ubuntu:latest"
}, {
    provider: provider
});

const container = new docker.Container("container", {
    image: remoteImage.imageId
}, {
    provider: provider
});
```

This fails with
```
Diagnostics:
  docker:index:RemoteImage (image):
    error: Docker native provider returned an unexpected error from Configure: error during connect: Get "http://docker.example.com/v1.24/plugins": command [ssh -- 123.45.67.89 docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
    Host key verification failed.
```
because the private key file is not used. I can connect fine when calling `ssh` manually with said arguments.

The `sshOpts` are not displayed as part of the `command [ssh - ...]` line which is why I assume they are not passed when trying to establish the connection. In earlier versions I could see the arguments as part of this line when I ran into an error.

### Output of `pulumi about`

```
CLI
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.3.1
hcloud  1.14.0
nodejs  unknown
tls     4.10.0

Host
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/linuxbrew/.linuxbrew/bin/node' version='v20.4.0'

Current Stack: <xxx>/test/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/<xxx>
User           <xxx>
Organizations  <xxx>

Dependencies:
NAME            VERSION
@pulumi/docker  4.3.1
@pulumi/hcloud  1.14.0
@pulumi/pulumi  3.76.1
@pulumi/tls     4.10.0
@types/node     16.18.39

Pulumi locates its logs in /tmp by default
```

### Additional context

This has worked fine in version 3.6.1 of the provider, but is not working in the current 4.3.1 release.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Thank you for filing this issue! We will take a look as soon as we can.

**Comment by TornjV** [comment]
Can confirm it's happening on our side too 👍

**Comment by guineveresaenger** [comment]
Hi @paschi - I have duplicated this.

It appears the provider currently ignores the content of the ssh flags, at least the `-i` and `-o` ones. It _does_ look in the default location of ~/home/.ssh for a `known_hosts` file with a valid entry. If such an entry exists, `pulumi up` succeeds for me. If I remove the remote host from the known hosts file, the provider ignores any valid key files I pass it.

I'm fairly certain these defaults are erroneously applied via the internal provider configuration, which shouldn't even affect your use case. Please stay tuned.
