### ISSUE TITLE
Remote connection issue via SSH for `RemoteImage` resources in `v4.3.1`

### ISSUE THREAD

**Issue by octet-stream** [pulumi/pulumi-docker#706]
### What happened?

After updating `@pulumi/docker` (npm package) to [`4.3.1`](https://github.com/pulumi/pulumi-docker/releases/tag/v4.3.1) my deployments started to constantly fail attempting to pull images for `RemoteImage` resource on remote server via SSH connection. https://github.com/pulumi/pulumi-docker/pull/697 seem to be responsible for the issue as it is the only change affecting `RemoteImage` resource and it seem to change the way pulumi picks address for `DOCKER_HOST`.

### Expected Behavior

Docker pulls images on remote machine without issues.

### Steps to reproduce

You can find reproduction steps in this repository: https://github.com/octet-stream/pulumi-remote-host-issue
It also includes ready to use pulumi project.

### Output of `pulumi about`

CLI          
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.3.1
docker  4.3.0
nodejs  unknown

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in nodejs:
version='v20.5.0'

Current Stack: octet-stream/pulumi-remote-host-issue/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/octet-stream
User           octet-stream
Organizations  octet-stream

### Additional context

Current solution is to stick on exact version of pulumi — [`4.3.0`](https://github.com/pulumi/pulumi-docker/releases/tag/v4.3.0)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @octet-stream. Thanks for letting us know about this, and for including such a thorough repro.
