### ISSUE TITLE
Support for docker save and load

### ISSUE THREAD

**Issue by JonCanning** [pulumi/pulumi-docker#713]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I am deploying the same image to dev, staging, and production environments and they all have independent infrastructure. I would like to use my CI server to create an image as an artifact in the build step using docker build and save, then during the deployment step use docker load and push. Since pulumi has the registry endpoint and credentials I would like to keep all these steps in code rather than having to export and shell.

**Comment by rquitales** [comment]
Thanks for filing this @JonCanning ! This sounds like a great suggestion to unlock new flows.

For anyone interested in this issue: upvoting helps my team prioritize; we're also open for contributions and can help shepherd a PR if anyone is interested.

CC @guineveresaenger in case you are aware of any duplicate requests for this.

**Comment by blampe** [comment]
Hi @JonCanning, we just released a new Docker Build provider focused exclusively on building images with buildx/BuildKit. It provides `--load` out of the box and should do what you need. We recommend you use it for building images going forward. Please take a look and give us feedback!

The repository is [here](https://github.com/pulumi/pulumi-docker-build); our blog announcement is [here](https://www.pulumi.com/blog/docker-build/); and finally API docs are [here](https://www.pulumi.com/registry/packages/docker-build/) along with examples of how to migrate your existing `Image` resources to `dockerbuild.Image`.

We won't be able to add this functionality in this provider for a number of reasons, so I'm closing this as wont-fix.
