### ISSUE TITLE
perma diff for docker.Image build field

### ISSUE THREAD

**Issue by KDanisme** [pulumi/pulumi-docker#715]
### What happened?

I have a docker.image resource which always shows a diff for the build field.

```
      + build: {
          + args          : {
              + BUILDKIT_INLINE_CACHE: "1"
            }
          + builderVersion: "BuilderBuildKit"
          + cacheFrom     : {
              + images: [
              +     [0]: "<omitted>"
                ]
            }
          + context       : "."
          + contextDigest : "0bfbd86619afaa013c3f1ad390303fe79f88348c11a8567d702cc0de2cd5aa3f"
          + dockerfile    : "<omitted>/Dockerfile"
          + platform      : "linux/amd64"
        }
```

### Expected Behavior

No diff if nothing changed.

### Steps to reproduce

```
new docker.Image( 
        "placeholder",
        {
            build: pulumi.output({
                platform: "linux/amd64",
                context: ".",
                cacheFrom: { images: ["placeholder"] },
                dockerfile: `${placeholder}/Dockerfile`,
                args: {
                    BUILDKIT_INLINE_CACHE: "1",
                },
            }),
            imageName: `${imagePath}:${tag}`,
            skipPush: false,
        },
        { provider: dockerProvider }
    )
```

### Output of `pulumi about`

```CLI
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Host
OS       arch
Version
Arch     x86_64
```
I am using automation api so i dont have a Pulumi.yaml

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @KDanisme thanks for getting in touch.

In order to have a complete reproduction please could you also share:
1. How you're configuring your provider (I notice you're using an explicitly declared provider)
2. An example docker image which will reproduce the issue (in case it's platform specify or relating to any other image-specific details).

Have you ever seen the resource go through an update without showing diff? Do you have any hypothesis as to which aspect of your resource's properties are causing the persistent diff?

Thanks in advance!

**Comment by KDanisme** [comment]
Hi @danielrbradley ,
I managed to reduce the issue:

```
new docker.Image("test", {
            build: {
                dockerfile: <a hardcoded string path to a dockerfile on my machine>,
            },
            imageName: `docker.io/test/test:test`,
            skipPush: true
    })
```
The dockerfile is simply:
```
FROM ubuntu:22.04
```

The diff is always 
```
     + build: {
          + builderVersion: "BuilderBuildKit"
          + contextDigest : "c927b92e3aa589ee801e990425cb92c0fcf37ffd1e7912421ee763b5581b3c8b"
          + dockerfile    : "<omitted>"
          + platform      : "linux/amd64"
        }      
```

**Comment by danielrbradley** [comment]
Thanks for getting back to me with those details @KDanisme 

I've just run the code now. The first deployment completed:

```
     Type                   Name         Status            Info
     pulumi:pulumi:Stack    scratch-dev                    
 +   └─ docker:index:Image  test         created (38s)     1 message
```

The second deployment deployment completed with:

```
     Type                   Name         Plan     Info
     pulumi:pulumi:Stack    scratch-dev           
     └─ docker:index:Image  test                  1 message


Diagnostics:
  docker:index:Image (test):
    Building your image for linux/arm64 architecture.
    To ensure you are building for the correct platform, consider explicitly setting the `platform` field on ImageBuildOptions.

Resources:
    2 unchanged
```

This doesn't appear to show the issue you're seeing with the persistent diff.

On editing the Dockerfile and re-running the deployment I saw something more similar to your diff:

```
Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::scratch::pulumi:pulumi:Stack::scratch-dev]
    ~ docker:index/image:Image: (update)
        [id=docker.io/test/test:test]
        [urn=urn:pulumi:dev::scratch::docker:index/image:Image::test]
        [provider=urn:pulumi:dev::scratch::pulumi:providers:docker::default_4_3_2::4dd03956-7eae-4a96-82d6-98b98d580dcc]
      + build: {
          + builderVersion: "BuilderBuildKit"
          + contextDigest : "2468faef8fcf559faae1d9c56721165657c23976d3cf7b1d338cb9f7e49fa7de"
          + dockerfile    : "docker/Dockerfile"
          + platform      : "linux/arm64"
        }
```

Running the deployment again, I was given a diff with no changes.

Is there any possibility that something in your environment could be changing which could be making docker think it needs to rebuild the image each time?

**Comment by KDanisme** [comment]
@danielrbradley the only thing i can thing of is that im using pulumi automation api, and the latest pulumi version.
But the diff when editing a dockerfile is also quite problematic concidering most of the things are the same besides the dockerfile hash

**Comment by KDanisme** [comment]
Do you need any more info? How can i help

**Comment by guineveresaenger** [comment]
Hi @KDanisme - this is almost certainly related to your Docker context somehow experiencing changes.

Can you explain more about what you mean by

> But the diff when editing a dockerfile is also quite problematic concidering most of the things are the same besides the dockerfile hash

Maybe I'm misunderstanding, but this is expected behavior: any change to the Dockerfile or its build context will trigger a rebuild of the image.

Can you send us a runnable reproduction using Automation API in a repo or a gist that we can use to look into this further?

**Comment by KDanisme** [comment]
Hi, @guineveresaenger , 
Sure ill get a repo ready.
What i mean is that in the diff stuff like the build platform are showing, even tho nothing changed regarding that field.

**Comment by KDanisme** [comment]
After some further tests,
Even doing `ignoreChanges: ["build"]` doesnt do anything, and diff is still happening
