### ISSUE TITLE
Default endpoint for Docker Desktop on Linux is not working

### ISSUE THREAD

**Issue by FPVian** [pulumi/pulumi-docker#720]
### What happened?

I'm getting the following error on linux: "Error pinging Docker server: Cannot connect to the Docker daemon at unix:///home/ian/.docker/run/docker.sock. Is the docker daemon running?"

I checked the docker endpoint for docker desktop using `docker context ls` and found that my endpoint is unix:///home/ian/.docker/desktop/docker.sock. This is the same as the default endpoint listed on [this page](https://docs.docker.com/desktop/faqs/linuxfaqs/#context), which the provider documentation links to.

Is there a way to configure the default endpoint? I have tried setting the DOCKER_HOST environment variable with no luck.

### Expected Behavior

I expected it to give me a diff and offer to build the container.

### Steps to reproduce

pulumi up

### Output of `pulumi about`

CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.3.0
docker        4.3.1
python        unknown

Host     
OS       linuxmint
Version  21.1
Arch     x86_64

This project is written in python: executable='/home/ian/github/sky-viz/.venv/bin/python3' version='3.10.6
'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/fpvian
User           fpvian
Organizations  fpvian

Dependencies:
NAME             VERSION
mypy-extensions  1.0.0
pip              23.1.2
psycopg-binary   3.1.9
setuptools       68.0.0
sky-viz          0.0.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Thank you for reporting this, @FPVian! Seems potentially related to #697. Would you be able to attach more verbose logs as documented [here](https://www.pulumi.com/docs/support/troubleshooting#diagnosing-issues)?

**Comment by FPVian** [comment]
For sure. I updated to 4.3.2 today just in case. I isolated the docker resource and set -v=11 and received the following output:

```
Updating (test)

View Live: https://app.pulumi.com/fpvian/sky-viz/test/updates/1


 +  pulumi:pulumi:Stack sky-viz-test creating (0s) 
@ Updating....
    docker:index:Image flights-image  error: 1 error occurred:
 +  pulumi:pulumi:Stack sky-viz-test created (0.36s) 
    docker:index:Image flights-image **failed** 1 error

Diagnostics:
  docker:index:Image (flights-image):
    error: 1 error occurred:
    	* Error pinging Docker server: Cannot connect to the Docker daemon at unix:///home/ian/.docker/run/docker.sock. Is the docker daemon running?

Resources:
    + 1 created

Duration: 2s
```

**Comment by thomas11** [comment]
Hi @FPVian, I suspect the problem is the `desktop-linux` Docker context. Does `docker context ls` show the contexts `default` and `desktop-linux`? If so, could you try using the default context for `pulumi up`?

If that works, we need to fix the Pulumi Docker provider to support the desktop context as well.

**Comment by FPVian** [comment]
Yes, I switched to default and still received the same error. It might be worth noting that my "default" docker endpoint is listed as:

 `unix:///var/run/docker.sock`

**Comment by thomas11** [comment]
That is really strange. We have CI tests running on Linux so I don't think this is generally broken.

[The code](https://github.com/pulumi/pulumi-docker/blob/7ed7b3223f8513c2ab38de6a4ba9ed1d1dd1a9a4/provider/image.go#L750) tries `unix:///var/run/docker.sock` first, and if that doesn't work, `unix://$HOME/.docker/run/docker.sock`. Both of those match yours.

Could it be a permission issue?

I actually just realized that your verbose log output above doesn't match what I expected. It should log
```
checking connection to docker daemon at unix:///var/run/docker.sock
no connection to docker daemon at unix:///var/run/docker.sock, trying unix:///home/ian/.docker/run/docker.sock
```
I'm not sure yet why you're not seeing that. Did you use `--logtostderr --logflow`?

**Comment by FPVian** [comment]
I don't think that the docker desktop endpoints match. Mine is `unix:///home/ian/.docker/desktop/docker.sock`. No I didn't...full log attached. Here's the bits from the logs you are looking for:

```
I0825 10:09:39.335271  227174 log.go:81] 2023/08/25 10:09:39 checking connection to docker daemon at unix:///var/run/docker.sock
I0825 10:09:39.335385  227174 log.go:81] eventSink::Debug(<{%reset%}>2023/08/25 10:09:39 checking connection to docker daemon at unix:///var/run/docker.sock<{%reset%}>)
I0825 10:09:39.336076  227174 log.go:81] 2023/08/25 10:09:39 no connection to docker daemon at unix:///var/run/docker.sock, trying unix:///home/ian/.docker/run/docker.sock (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?)
I0825 10:09:39.336111  227174 log.go:81] eventSink::Debug(<{%reset%}>2023/08/25 10:09:39 no connection to docker daemon at unix:///var/run/docker.sock, trying unix:///home/ian/.docker/run/docker.sock (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?)<{%reset%}>)
I0825 10:09:39.336396  227174 log.go:81] 2023/08/25 10:09:39 Setting DOCKER_HOST to unix:///home/ian/.docker/run/docker.sock
I0825 10:09:39.336414  227174 log.go:81] eventSink::Debug(<{%reset%}>2023/08/25 10:09:39 Setting DOCKER_HOST to unix:///home/ian/.docker/run/docker.sock<{%reset%}>)
```
[out.txt](https://github.com/pulumi/pulumi-docker/files/12440354/out.txt)

**Comment by thomas11** [comment]
```
unix:///home/ian/.docker/desktop/docker.sock
unix:///home/ian/.docker/run/docker.sock

unix:///var/run/docker.sock
unix:///var/run/docker.sock
```

I see - the endpoints in $HOME are different, "desktop" vs "run". The system-wide ones match, though. Not sure why that didn't work.

**Comment by FPVian** [comment]
That may be because I don't have a docker engine installed outside of docker desktop? I propose that we add a check for the default linux location to your rewrite of the `configureDockerClient()` function. Please bear in mind that I have never used Go before...
