### ISSUE TITLE
Add clarity to build instructions

### ISSUE THREAD

**Issue by FPVian** [pulumi/pulumi-docker#768]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I ran into a couple things that weren't 100% clear when trying to follow the instructions for contributing. Normally this wouldn't be a problem, but I had unlucky timing, so it was difficult to figure out what I was doing wrong.

1. Which make commands to use in different situations. This is covered in the "Make build system" section of pulumi/CONTRIBUTING.md, but since it isn't standardized across projects it led to some confusion.

2. That adding the /bin folder for this repo to the PATH is the fastest way to test new providers. Once again, this is covered in the "Make build system" section, but it's not really clear how that applies to pulumi-docker as well.

### Affected area/feature

CONTRIBUTING.md

**Comment by mikhailshilkov** [comment]
@FPVian Thank you for filing this! Any chance you could open a PR while the experience is still fresh in your memory? Thank you for being an active community member, we really appreciate that!

**Comment by FPVian** [comment]
Alrighty, I took a shot at it.
