### ISSUE TITLE
Image's `outputs.__inputs` are not properly encrypted in the statefile

### ISSUE THREAD

**Issue by mike-chen-samsung** [pulumi/pulumi-docker#772]
### What happened?

The behavior I'm seeing is identical to: https://github.com/pulumi/pulumi-kubernetes/issues/915

### Example

```
new Image('deleteme',
  {
    build: {
      args: {
        SOMESECRET: secret('hello'),
      },
    },
    imageName: 'some_repo:deleteme',
  },
)
```

with Dockerfile:
```
FROM busybox
```

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.83.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.42.0
docker      4.4.1
kubernetes  4.2.0
nodejs      unknown

Host     
OS       darwin
Version  12.5
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
This is now fixed in [v4.4.2](https://github.com/pulumi/pulumi-docker/tree/v4.4.2)
