### ISSUE TITLE
The `repoDigest` output sometimes does not update on builds

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-docker#812]
### What happened?

When building a new Image, and logs show that the image was built and pushed to the remote registry, the `repoDigest` output sometimes does not change. This occurs only when the image name and tag (`imageName`) is  consistent between builds, suggesting either a race condition in either our provider or the Docker engine.

### Example

Build an image with the same `imageName` repeatedly, and an output printing the `repoDigest`. The `repoDigest` rarely will not show an update.

### Output of `pulumi about`

Latest Docker & Pulumi as of 10/25/2023

### Additional context

The relevant section of the build implementation:
1. Runs the `ImagePush` RPC against the Docker Engine
2. Streams the output
3. Runs the `InspectImageWithRaw` RPC against the Docker Engine, retrieving the image with the `imageName` property

By line 390 below, I would expect the engine's image store to have updated, and the `imageName` should refer to the newly built image. It appears that sometimes the result of the call returns the _previously_ built image.

https://github.com/pulumi/pulumi-docker/blob/902ce25e0df6a3c921629887e2f4015a3c0201d8/provider/image.go#L361-L391

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@AaronFriel Can you help me repro this?

I started with https://github.com/pulumi/pulumi-docker/blob/master/examples/azure-container-registry/ts/index.ts but added `export const dgst = image.repoDigest;` to the end.

I deployed it ten times, each time changing `Dockerfile` a little bit, and the digest got updated consistently. Any idea how to repro?

**Comment by mikhailshilkov** [comment]
I'll remove P1 given we are still trying to reproduce the issue reliably. We haven't seen any customer impact yet, except for internal usage. Some progress is in https://github.com/pulumi/pulumi-docker/pull/828.

**Comment by danielbichuetti** [comment]
Hello @mikhailshilkov . I found the same issue. 

The problem seems to be related somehow to the state. If we change the Dockerfile, it will work. But if we change the login_server, it will point to the old one. 
We use it with ACR.

**Comment by AaronFriel** [comment]
@danielbichuetti I think you are running into #778.

**Comment by danielbichuetti** [comment]
It may be. It's the second issue with ACR that we face.

These issues are being so problematic for our deployments.

I hope you can fix it as soon as possible.

**Comment by joeduffy** [comment]
@AaronFriel Have we seen additional occurrences of this recently?

**Comment by AaronFriel** [comment]
@joeduffy We have, I'll send you a DM with the internal issue. 

I tried digging in a little deeper this morning, and I'll have a PR this morning to:
1. Fix #812 by detecting and handling a race, if the hypothesis is correct; and to fail the build if we would return an incorrect repoDigest with additional logging to help debug in the failure case
2. Fix #778

**Comment by joeduffy** [comment]
Ok, great, thanks. I am mostly wondering if we've narrowed this down to

1. A bug in Docker
2. A bug in the Pulumi Docker Provider
3. A bug elsewhere, like in Pulumi Deployments sharing a cache or something, which triggers this

It sounds like you're hypothesizing (2).
