### ISSUE TITLE
skip push or updating an image if it already exists in the remote registry

### ISSUE THREAD

**Issue by dkezri** [pulumi/pulumi-docker#824]
## skip push for existing image in remote registry e.g.  (azure container registry)

I have an application docker image that is already pushed to  azure container registry. When i try to run  "pulumi up" next time to create other azure resources,  it also overwrites the existing docker image with a base template image which is used for creating new applications.  how we  can apply a conditional "skippush"  for existing images in  azure container registry ?

**Comment by mikhailshilkov** [comment]
@dkezri Could you please provide a code snippet to illustrate the scenario that you are referring to?

**Comment by dkezri** [comment]
## The code to create the image from a dockerfile  as template:

`
 public  Docker.Image CreateContainerImage(Registry registry,
     string imageName, 
     Output<string> adminUserName, 
     Output<string> adminPassword,
     string imageTag = "v1.0.0")
 {
     var image = new Docker.Image($"{imageName}-image", new()
     {
         ImageName = Output.Format($"{registry.LoginServer}/{imageName}:{imageTag}"),
         //SkipPush= true,
         Build = new DockerBuildArgs
         {
             Context = "./",
             Platform = "linux/amd64",
             //Args= { "BUILDKIT_INLINE_CACHE", "1"},
             CacheFrom = new CacheFromArgs
             {
                 Images = imageName,
             }
         },
         Registry = new Docker.Inputs.RegistryArgs
         {
             Server = registry.LoginServer,
             Username = adminUserName,
             Password = adminPassword,
         },
     },
       new CustomResourceOptions
       {
           DependsOn = registry,
           IgnoreChanges = new List<string> { imageName }
       }
     );
     return image;
 }
`

##The content of the Dockerfile:
`
FROM nginx
RUN echo "<center><h1>Hello, World!</h1></center>" > \
    /usr/share/nginx/html/index.html
`

##  The image used in  azurenative.App.ContainerApp:

`
  var image = CreateContainerImage(registry, "acrUsername","acrUserPass" , "applicationname");
 var containerApp = new ContainerApp(containerName, new()
{
     Template = new TemplateArgs
  {
      Containers = new List<ContainerArgs>
      {
          new ContainerArgs
          {
              Name = name,
              Image =image.ImageName,
              Resources = new ContainerResourcesArgs()
              {
                  Cpu = Config.ContainerCpu,
                  Memory = Config.ContainerMemory,
              },
              Env = new List<EnvironmentVarArgs>()
              {
                  AddEnvironmentVarArgs("ASPNETCORE_ENVIRONMENT",Config.GetEnvironment),
              },
          },
      },

}
`

**Comment by mikhailshilkov** [comment]
@dkezri Another follow-up clarification - your implementation of `CreateContainerImage` doesn't seem to match your call: the former has arguments `registry, imageName, adminUserName, adminPassword, imageTag?` while you call it with `registry, "acrUsername","acrUserPass" , "applicationname"`... I suspect `acrUsername` isn't your image name, so something is mixed up?

**Comment by dkezri** [comment]
@mikhailshilkov   you are write, the applicationname is the imagename as i changed it above.

**Comment by mikhailshilkov** [comment]
@dkezri Thank you for the clarification.

I have a theory for why you get diffs in `build`. You have `Context` pointing to the same folder where your Pulumi program resides: `Context = "./",`. That means that the context digest (hashsum) is going to change every time anything changes in that folder, including the program itself. I'd recommend you move your `Dockerfile` to a separate subfolder (e.g. `app`) and then set the context to it: `Context = "./app",`. Do you want to give it a try?

**Comment by dkezri** [comment]
@mikhailshilkov  thank you for the solution, i moved  the dockefile and its related json files to a folder named "Templates" inside my  .Net project and it worked nice.

**Comment by dkezri** [comment]
this issue can be closed now
