### ISSUE TITLE
Allow using Docker images that are already built locally

### ISSUE THREAD

**Issue by rlukata** [pulumi/pulumi-docker#835]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When using `new docker.Image`, check if there's an are already built image locally instead of having to rebuild them.

### Affected area/feature

Docker

**Comment by mikhailshilkov** [comment]
Hi @rlukata Could you please provide a little bit more details about your idea? What is the main motivation to do so? Can you describe a use case where you would expect this to work? I expect there may be some difficulties in understanding whether a local image can be reused or not in all cases, but maybe you have a very specific scenario in mind?

**Comment by rlukata** [comment]
We heavily use S3 caching (cache-to and cahce-from) in CI, and since the `pulumi-docker` v4 API hasn't implemented these buildx features yet, we're having to build the images outside of pulumi. At the same time, we also have multiple resources that rely on those images being built and pushed to the registry.

I think that it would greatly simplify the orchestration and would be an elegant way to manage resource dependencies/relationships if I could build the images outside of pulumi -to leverage the ever-changing buildx features, and then use pulumi to push/deploy these images.

**Comment by blampe** [comment]
> and since the pulumi-docker v4 API hasn't implemented these buildx features yet

Hi @rlukata, we just released a new Docker Build provider focused exclusively on building images with buildx/BuildKit. It should provide all of the buildx features you need, and we recommend you use it for building images going forward. Please take a look and give us feedback!

The repository is [here](https://github.com/pulumi/pulumi-docker-build); our blog announcement is [here](https://www.pulumi.com/blog/docker-build/); and finally API docs are [here](https://www.pulumi.com/registry/packages/docker-build/) along with examples of how to migrate your existing `Image` resources to `dockerbuild.Image`.

We won't be able to add this functionality in this provider for a number of reasons, so I'm closing this as wont-fix.
