### ISSUE TITLE
Add support for `--network` in Pulumi Docker v4 using `BuilderV1`

### ISSUE THREAD

**Issue by uatach** [pulumi/pulumi-docker#837]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Similar to #761, the `--network` flag was removed from `docker.DockerBuild` which is leaving us pinned at v3.
I also reported this problem in https://github.com/pulumi/pulumi-docker/issues/424#issuecomment-1470894545.
For our case specifically, in Google Cloud when building a Docker image that needs a Python package hosted at Artifact Registry, we need credentials that are accessible from the `cloudbuild` network.

From what I understand reading https://github.com/docker/buildx/issues/175, and specifically https://github.com/docker/buildx/issues/175#issuecomment-1062837588, BuildKit won't be adding support for custom networks anytime soon and the workaround needs a hard-coded IP from Google's metadata server to be used with the `--add-host` flag.
There's also an issue at https://issuetracker.google.com/issues/227640666 that has not been addressed yet.

The other option would be to add the `--network` flag back, to be used with the `BuilderV1`.

**Comment by uatach** [comment]
I would be happy to implement a solution for this.

**Comment by mikhailshilkov** [comment]
> I would be happy to implement a solution for this.

That would be great. Do you have a concrete plan how to bring this support to the current V4? If so, let's try to describe it in this issue first.

**Comment by uatach** [comment]
@mikhailshilkov no, I don't have a concrete plan.

**Comment by uatach** [comment]
The issue at https://issuetracker.google.com/issues/227640666 has been marked as "Fixed" but it's not clear what was fixed or how it's supposed to work now...

Still, I created a new project using Pulumi Docker v4 but, again, when trying to install a Python package from Artifact Registry, it is unable to acquire the  credentials from the metadata server...

Following the discussion from https://github.com/docker/buildx/issues/175, it seems that BuildKit now has the `--network` flag again but it has some DNS resolution problems.

**Comment by uatach** [comment]
I've created a new project using Pulumi Docker v4.5.3 to test the network option but it gave an error:
> error: error building image: Error response from daemon: network mode "cloudbuild" not supported by buildkit

I'm not sure what is the problem, if it's related to Pulumi Docker or to the buildkit running on Google Cloud Build
