### ISSUE TITLE
Github actions support

### ISSUE THREAD

**Issue by andy9775** [pulumi/pulumi-docker#84]
Trying to execute a cloud service and pointing to a local docker file causes the following error when run in Github Actions:
```
Executing 'docker image inspect -f {{.Id}} pulum-t7a9591-container'


error: Error response from daemon: This Docker operation is forbidden by GitHub Actions, you can find documentation at https://developer.github.com/actions/

```

This is using `@pulumi/cloud-aws`

**Comment by ellismg** [comment]
This problem is not specific to `@pulumi/cloud-aws`, it's due to `@pulumi/docker` needing to run `docker image inspect` which is disallowed when running in the environment provided by GitHub actions.

**Comment by lukehoban** [comment]
I'm not sure there is anything we can do here - the scenario in question is fundmantally not supported in GitHub Actions.  I think pretty much any fix here would need to be in Actions support for `docker`.
