### ISSUE TITLE
Support building a docker image without pushing

### ISSUE THREAD

**Issue by Place1** [pulumi/pulumi-docker#85]
My use-case is developing with a local minikube cluster. I would like to build a docker image directly on the minikube VM so that I can run my app on the cluster without requiring a registry.

The use-case is similar to what [skaffold](https://github.com/GoogleContainerTools/skaffold) does incase anyone is familiar.

Perhaps the `docker.Image` resource could support a `skipPush: true`? or perhaps it could skip the push step if `imageName` is undefined?

**Comment by lukehoban** [comment]
This is interestingly the opposite of https://github.com/pulumi/pulumi-docker/issues/54.

**Comment by tedchangtr** [comment]
We would find this feature useful as well for local development.

**Comment by koper89** [comment]
Yes this would be extremely useful for replacing docker-compose for local dev environment creation. Ideally if it would be possible to change Container type to accept either image (in registry) or build from Dockerfile similar like docker-compose does.

**Comment by koper89** [comment]
This pull request on terraform is kinda interesting:
https://github.com/terraform-providers/terraform-provider-docker/pull/133

**Comment by lukehoban** [comment]
This was actually fixed in #114.  Thanks @koper89 !
