### ISSUE TITLE
Docker Build Cloud support

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-docker#956]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be awesome, if the Pulumi Docker provider had support for the new Docker Build Cloud.

To build using Docker Build Cloud, invoke a build command and specify the name of the builder using the --builder flag.

 `docker buildx build --builder cloud-ORG-BUILDER_NAME --tag IMAGE .`

This is currently not possible to do the provider.

See -> https://docs.docker.com/build/cloud/ for more details!

### Affected area/feature

Provider

**Comment by blampe** [comment]
Available in the new Docker Build provider. The repository is [here](https://github.com/pulumi/pulumi-docker-build); our blog announcement is [here](https://www.pulumi.com/blog/docker-build/); and finally API docs are [here](https://www.pulumi.com/registry/packages/docker-build/) along with an example of how to use it with DBC.

We won't be able to add this functionality in this provider for a number of reasons, so I'm closing this as wont-fix.
