### ISSUE TITLE
Cannot specify port in image name

### ISSUE THREAD

**Issue by ameier38** [pulumi/pulumi-docker#97]
I cannot specify a docker registry server port as pulumi thinks I am defining a tag.

```ts
const myImage = new docker.Image(
    'my-image',
    {
        imageName: 'docker.mycompany.com:5000/namespace/myimage:latest',
        registry: dockerRegistry,
        build: path.join(ROOT_DIR, 'myimage')
    }
)
```
> This should be a valid image name but pulumi throws an error `Error: [repositoryUrl] should not contain a tag` (note the two colons)

I would like to propose adding another image arg `registryServer` such as 
```ts
const myImage = new docker.Image(
    'my-image',
    {
        imageName: 'namespace/myimage:latest',
        registryServer: 'docker.mycompany.com:5000',
        registry: dockerRegistry,
        build: path.join(ROOT_DIR, 'myimage')
    }
)
```
This way it would be easier to parse the image name and tag without having to figure out if the colon specifies a port or a tag.

**Comment by CyrusNajmabadi** [comment]
@ameier38 why can't the `docker.mycompany.com:5000` be specified in your `dockerRegistry.server` property?  Thanks!

**Comment by ameier38** [comment]
@CyrusNajmabadi unfortunately that did not work. I changed the image def to 
```ts
const myImage = new docker.Image(
    'my-image',
    {
        imageName: 'namespace/myimage:latest',
        registry: {
            server: 'docker.mycompany.com:5000',
            username: 'admin',
            password: 'secret'
        },
        build: path.join(ROOT_DIR, 'myimage')
    }
)
```
But when running `pulumi up` docker will try to push the image to `namespace/myimage:latest` instead of `docker.mycompany.com:5000/namespace/myimage:latest`. The `imageName` property seems like it needs to be fully qualified with the registry server.

**Comment by CyrusNajmabadi** [comment]
you're correct.  we'll have to provide a sepcific way to handle this.  another option would be to have the 'tag' detection check if it's a number, but that seems like it could get full of hacks that we wouldn't want.
